### ISSUE TITLE
[Error: double colon in host identifier]

### ISSUE THREAD

**Issue by okaris** [ParsePlatform/parse-server#1002]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

parse-server-example 2.1.4 running on Heroku
database running on mLab shared cluster

#### Steps to reproduce
MONGOLAB_URI : mongodb://<dbuser>:<dbpassword>@ds059645-a0.mongolab.com:59645,ds059645-a1.mongolab.com:59645/<dbname>?replicaSet=rs-ds059645

https://github.com/ParsePlatform/parse-server/issues/855
@gfosco 

#### Logs/Trace

`2016-03-12T17:21:07.174007+00:00 heroku[web.1]: Starting process with command `npm start`
2016-03-12T17:21:08.712950+00:00 app[web.1]: 
2016-03-12T17:21:08.712960+00:00 app[web.1]: > parse-server-example@1.2.0 start /app
2016-03-12T17:21:08.712961+00:00 app[web.1]: > node index.js
2016-03-12T17:21:08.712961+00:00 app[web.1]: 
2016-03-12T17:21:10.105043+00:00 app[web.1]: parse-server-example running on port 27750.
2016-03-12T17:21:10.573179+00:00 heroku[web.1]: State changed from starting to up
2016-03-12T17:21:26.759620+00:00 app[web.1]: [Error: double colon in host identifier]
2016-03-12T17:21:56.747283+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/parse/classes/Waves" host=coralline.herokuapp.com request_id=d94cfa43-8644-4d30-a684-71fdef946cc8 fwd="178.240.162.250" dyno=web.1 connect=1ms service=30205ms status=503 bytes=0`

**Comment by flovilmart** [comment]
It seems that you have 2 servers specified in your MONGOLAB_URI, is that one purpose?

**Comment by okaris** [comment]
@flovilmart Yes it's a replica set on mLab. I took the connection string directly form them. I also tried using only one of the database url's, but I still have the same problem. If you check out the issue i referred there is a bug in the mongo driver actually but it is strange that no one else is having the same problem.

**Comment by flovilmart** [comment]
can you test on that branch about to be merged? https://github.com/ParsePlatform/parse-server/pull/986

**Comment by okaris** [comment]
I'm not sure how I can use that branch on parse-server since the driver is added as an npm dependency. If you can point me in a direction of how to, I'd be glad.

**Comment by flovilmart** [comment]
if this is a mongo driver problem, please post the issue to the mongo people :)

**Comment by okaris** [comment]
@flovilmart I tried to use that branch you offered by changing the dependency in parse-server-example package.json to    
`"parse-server": "git+https://github.com/ParsePlatform/parse-server.git#mongo-uri-encode-auth"
`

All I get is 
`Error: Cannot find module 'parse-server'
`

Can you help me build with that branch please?

**Comment by okaris** [comment]
The branch at https://github.com/ParsePlatform/parse-server/pull/986 seems to help. It appears that mongo driver can't parse a password with a column ',' in it. This branch seems to fix it or another option is to avoid '@,:' in your database username or password. 

Also mongo driver doesn't accept replica set connection strings obtained from mLab. The connection string needs to have only one database url in it.

This issue and related issue https://github.com/ParsePlatform/parse-server/issues/855 can be closed now.

**Comment by kartheeknagasuri** [comment]
hello, i am still facing this issue, any suggestions?

my DB connection string is 

mongodb://username:password@7163360509808/iad2-c5-1.mongo.objectrocket.com:port/preprod


at new Promise (/var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
    at Function.MongoClient.connect (/var/app/current/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:104:12)
    at MongoStorageAdapter.connect (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:128:44)
    at MongoStorageAdapter._schemaCollection (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:163:19)
    at MongoStorageAdapter.getAllClasses (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:312:19)
    at /var/app/current/node_modules/parse-server/lib/Controllers/SchemaController.js:354:34
    at run (/var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
ESC[33mwarnESC[39m: Unable to ensure uniqueness for user email addresses:  Error: double colon in host identifier
    at module.exports (/var/app/current/node_modules/parse-server/node_modules/mongodb/lib/url_parser.js:91:13)
    at connect (/var/app/current/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:266:16)
    at /var/app/current/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:105:7
    at new Promise (/var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:191:7)
    at Function.MongoClient.connect (/var/app/current/node_modules/parse-server/node_modules/mongodb/lib/mongo_client.js:104:12)
    at MongoStorageAdapter.connect (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:128:44)
    at MongoStorageAdapter._schemaCollection (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:163:19)
    at MongoStorageAdapter.getAllClasses (/var/app/current/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoStorageAdapter.js:312:19)
    at /var/app/current/node_modules/parse-server/lib/Controllers/SchemaController.js:354:34
    at run (/var/app/current/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
parse-server-example running on port 8081.
