### ISSUE TITLE
Parse locally setup error

### ISSUE THREAD

**Issue by patelvishal1401** [ParsePlatform/parse-server#1018]
I have done this step

$ npm install -g parse-server mongodb-runner
$ mongodb-runner start
$ parse-server --appId APPLICATION_ID --masterKey MASTER_KEY

Give app id 123 and masterkey 123

It gives error like : 

module.js:329
    throw err;
    ^

Error: Cannot find module '/Users/vishal/123'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/parse-server/lib/cli/parse-server.js:59:13)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)

How can i solve this

**Comment by flovilmart** [comment]
What is the exact command that your run in your terminal?

**Comment by patelvishal1401** [comment]
$ parse-server --appId APPLICATION_ID --masterKey MASTER_KEY

**Comment by flovilmart** [comment]
you should set APPLICATION_ID to your applicationId and MASTER_KEY to your masterKey

**Comment by patelvishal1401** [comment]
i have done, after its give error like : 

module.js:329
throw err;
^

Error: Cannot find module '/Users/vishal/123'
at Function.Module._resolveFilename (module.js:327:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:355:17)
at require (internal/module.js:13:17)
at Object. (/usr/local/lib/node_modules/parse-server/lib/cli/parse-server.js:59:13)
at Module._compile (module.js:399:26)
at Object.Module._extensions..js (module.js:406:10)
at Module.load (module.js:345:32)
at Function.Module._load (module.js:302:12)
at Module.require (module.js:355:17)

**Comment by flovilmart** [comment]
for some odd reason, the cli thinks your master key is the path to a json file, try:

parse-server --appId=APPLICATION_ID --masterKey=MASTER_KEY

**Comment by patelvishal1401** [comment]
Ya, Thanks its start now, but give new error can you help me in this.

Thanks.. for your help, i am trying to solve from last 1 day..

<img width="300" alt="screen shot 2016-03-14 at 9 37 01 pm" src="https://cloud.githubusercontent.com/assets/6769381/13750779/f38de888-ea2c-11e5-9f18-a00de146b40d.png">

**Comment by flovilmart** [comment]
This is unauthorized because you're not setting the proper headers in your request.
Please refere here : https://github.com/ParsePlatform/parse-server#getting-started

**Comment by patelvishal1401** [comment]
Ok, done, thanks @flovilmart , You save my day..

**Comment by gowridev** [comment]
Error: Cannot find module '../lib/cli/parse-server' . I  am getting this error, when I am trying to deploy in it on ibm bluemix. Could you please guide me regarding this. (i cloned git repository into my local system and push it using "cf push" command.)

2016-03-21T18:05:21.373+0530[App/0]ERR at Module.require (module.js:353:17)
2016-03-21T18:05:21.373+0530[App/0]ERR at Module.load (module.js:343:32)
2016-03-21T18:05:21.372+0530[App/0]ERR ^
2016-03-21T18:05:21.373+0530[App/0]ERR at require (internal/module.js:12:17)
2016-03-21T18:05:21.373+0530[App/0]ERR at Module._compile (module.js:409:26)
2016-03-21T18:05:21.372+0530[App/0]ERRmodule.js:327
2016-03-21T18:05:21.373+0530[App/0]ERR at Function.Module.runMain (module.js:441:10)
2016-03-21T18:05:21.373+0530[App/0]ERR at Object.<anonymous> (/home/vcap/app/bin/parse-server:3:1)
2016-03-21T18:05:21.373+0530[App/0]ERR at Function.Module._load (module.js:276:25)
2016-03-21T18:05:21.373+0530[App/0]ERR at Object.Module._extensions..js (module.js:416:10)
2016-03-21T18:05:21.373+0530[App/0]ERR at Function.Module._resolveFilename (module.js:325:15)
2016-03-21T18:05:21.373+0530[App/0]ERRError: Cannot find module '../lib/cli/parse-server'
2016-03-21T18:05:21.373+0530[App/0]ERR at Function.Module._load (module.js:300:12)
2016-03-21T18:05:21.372+0530[App/0]ERR throw err;
2016-03-21T18:05:21.380+0530[App/0]OUT
2016-03-21T18:05:21.495+0530[DEA/92]ERRInstance (index 0) failed to start accepting connections

**Comment by gfosco** [comment]
try building it first with: `npm run build`

**Comment by gowridev** [comment]
I have used the below command 
cf push parse-server-four -b sdk-for-nodejs -n parse-server-third  -m 1024M -c 'npm run build'

I am getting this error

2016-03-22T11:58:43.85+0530 [STG/0]      OUT -----> Build succeeded!
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── apn@1.7.5
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── aws-sdk@2.2.45
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── babel-polyfill@6.7.2
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── babel-runtime@6.6.1
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── bcrypt-nodejs@0.0.3
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── body-parser@1.15.0
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── colors@1.1.2
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── commander@2.9.0
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── deepcopy@0.6.1
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── express@4.13.4
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── gcloud@0.28.0
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── mailgun-js@0.7.7
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── mime@1.3.4
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── mongodb@2.1.10
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── multer@1.1.0
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── node-gcm@0.14.0
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── parse@1.8.1
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        ├── request@2.69.0
2016-03-22T11:58:44.61+0530 [STG/0]      OUT        └── winston@2.2.0
2016-03-22T11:58:44.62+0530 [STG/0]      ERR 
2016-03-22T11:58:51.85+0530 [STG/24]     OUT -----> Uploading droplet (29M)
2016-03-22T11:59:01.40+0530 [DEA/24]     OUT Starting app instance (index 0) with guid 029918b6-d0d3-4fbe-9550-202f39cb9ff4
2016-03-22T11:59:14.06+0530 [App/0]      OUT 
2016-03-22T11:59:14.06+0530 [App/0]      OUT > parse-server@2.1.6 build /home/vcap/app
2016-03-22T11:59:14.06+0530 [App/0]      OUT > babel src/ -d lib/
2016-03-22T11:59:14.07+0530 [App/0]      ERR sh: 1: babel: not found
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! Linux 3.19.0-25-generic
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "run" "build"
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! node v4.3.2
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! npm  v2.14.12
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! file sh
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! code ELIFECYCLE
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! errno ENOENT
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! syscall spawn
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! parse-server@2.1.6 build: `babel src/ -d lib/`
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! spawn ENOENT
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! 
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! Failed at the parse-server@2.1.6 build script 'babel src/ -d lib/'.
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! This is most likely a problem with the parse-server package,
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! not with npm itself.
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! Tell the author that this fails on your system:
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR!     babel src/ -d lib/
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! You can get their info via:
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR!     npm owner ls parse-server
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! There is likely additional logging output above.
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR! Please include the following file with any support request:
2016-03-22T11:59:14.09+0530 [App/0]      ERR npm ERR!     /home/vcap/app/npm-debug.log
2016-03-22T11:59:14.18+0530 [DEA/24]     ERR Instance (index 0) failed to start accepting connections
2016-03-22T11:59:14.21+0530 [API/4]      OUT App instance exited with guid 029918b6-d0d3-4fbe-9550-202f39cb9ff4 payload: {"cc_partition"=>"default", "droplet"=>"029918b6-d0d3-4fbe-9550-202f39cb9ff4", "version"=>"abf47b2d-6cdd-43e2-ba73-e5d5fa8c3e21", "instance"=>"2d991a20aadf4f50bb2cae06c8e67203", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1458628154}
2016-03-22T11:59:14.21+0530 [API/7]      OUT App instance exited with guid 029918b6-d0d3-4fbe-9550-202f39cb9ff4 payload: {"cc_partition"=>"default", "droplet"=>"029918b6-d0d3-4fbe-9550-202f39cb9ff4", "version"=>"abf47b2d-6cdd-43e2-ba73-e5d5fa8c3e21", "instance"=>"2d991a20aadf4f50bb2cae06c8e67203", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"failed to accept connections within health check timeout", "crash_timestamp"=>1458628154}
2016-03-22T11:59:58.07+0530 [DEA/177]    OUT Starting app instance (index 0) with guid 029918b6-d0d3-4fbe-9550-202f39cb9ff4
