### ISSUE TITLE
TypeError: res.sendFile is not a function

### ISSUE THREAD

**Issue by jaydeep82** [ParsePlatform/parse-server#1091]
For implementation related questions or technical support, please refer to the [stackoverflow](http://stackoverflow.com/questions/tagged/parse.com) community.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Server!

- [x] You've met the [prerequisites](https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites).

- [x] You're running the [latest version](https://github.com/ParsePlatform/parse-server/releases) of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-server/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Heroku + MongoLab

#### Steps to reproduce

I have deployed parse on Heroku and I'm able to call the all cloud functions.

When call with '/' it's working showing 'I dream of being a web site.'
But when I call https://myapp-dev2.herokuapp.com/test in browser, it showing error 

```
app.get('/', function(req, res) {
  res.status(200).send('I dream of being a web site.');
});

app.get('/test', function(req, res) {
   //res.sendFile('/app/public/index.html');
   res.sendFile('public/index.html', { root: __dirname });
});
```
#### Logs/Trace

```
2016-03-18T15:12:54.734560+00:00 app[web.1]: TypeError: res.sendFile is not a function
2016-03-18T15:12:54.734603+00:00 app[web.1]:     at Object.handle (/app/index.js:68:8)
2016-03-18T15:12:54.734613+00:00 app[web.1]:     at next_layer (/app/node_modules/express/lib/router/route.js:103:13)
2016-03-18T15:12:54.734614+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:107:5)
2016-03-18T15:12:54.734615+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:205:24
2016-03-18T15:12:54.734615+00:00 app[web.1]:     at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:269:12)
2016-03-18T15:12:54.734616+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:199:19)
2016-03-18T15:12:54.734616+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:176:38)
2016-03-18T15:12:54.734617+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/index.js:176:38)
2016-03-18T15:12:54.734617+00:00 app[web.1]:     at Layer.expressInit [as handle] (/app/node_modules/express/lib/middleware/init.js:23:5)
2016-03-18T15:12:54.734618+00:00 app[web.1]:     at trim_prefix (/app/node_modules/express/lib/router/index.js:240:15)
```

**Comment by gfosco** [comment]
From the express docs: `res.sendFile() is supported by Express v4.8.0 onwards`

I assume this is your issue, as it's not related to parse-server.

**Comment by gfosco** [comment]
You can update your package json to require a newer version of express.

**Comment by mdere** [comment]
This was the fix!!! glad I found this.

**Comment by SudhirKaushik** [comment]
Update version to 4.8.0. Still getting error.

**Comment by chansudh02** [comment]
const express=require('express');
const mysql=require('mysql2')
const path = require('path');


const app=express();

const db=mysql.createConnection({
    host:'localhost',
    user:'root',
    password:'root',
    database:'school'
});

db.connect((err)=>{
    if(err){
        console.error('error connecting',err);
        process.exit(1);
    }
    console.log('connected as id'+db.threadId);
});

app.use(express.urlencoded({extended:true}));

const validateInput=(input)=>{
    const trimmedInput=input.trim();
    if (trimmedInput.length===0){
        throw new error('input cannot be empty');        
    }
    return mysql.escape(trimmedInput);
};

app.post('/submit',(req,res) => {
    try{
        const username=validateInput(req.body.username);
        const query="INSERT INTO table1(sname) VALUES (?)";
        db.query(query,[username],(err,results)=>{
            if(err){
                console.error('error runing query',err);
                res.status(500).send('error inserting data');
            }
            else{
                res.send('inserted data ${username}');
            }
        });
    }
    catch(error){
        console.error('validatinginput',error);
        res.status(400).send('invalid input');
    }
});

app.get('/',(res,req)=>{
    res.sendfile(path.join(__dirname+'/index.html'));
});
const port = 9000;
app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});

**Comment by chansudh02** [comment]
what error in this node js file
