### ISSUE TITLE
v2.2.1 breaks LiveQuery

### ISSUE THREAD

**Issue by skimgosu** [ParsePlatform/parse-server#1147]
Played around with v2.2.0 for LQ. Updated to 2.2.1 and this popped up. I really gotta get around to learning JS or at least using a proper IDE/editor other than TextEdit so I can fix it myself!

2016-03-23T07:53:25.252577+00:00 app[web.1]: TypeError: ParseServer.createLiveQueryServer is not a function
2016-03-23T07:53:25.252578+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:59:15)
2016-03-23T07:53:25.252579+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-03-23T07:53:25.252579+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-03-23T07:53:25.252580+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-03-23T07:53:25.252580+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-03-23T07:53:25.252581+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-03-23T07:53:25.252582+00:00 app[web.1]:     at startup (node.js:141:18)
2016-03-23T07:53:25.252582+00:00 app[web.1]:     at node.js:933:3
2016-03-23T07:53:25.262226+00:00 app[web.1]: Worker 28 died.. Restarting

**Comment by flovilmart** [comment]
What does your index file look like?

**Comment by skimgosu** [comment]
2016-03-23T12:18:17.446879+00:00 app[web.1]: TypeError: ParseServer.createLiveQueryServer is not a function
2016-03-23T12:18:17.446880+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:52:15)
2016-03-23T12:18:17.446880+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-03-23T12:18:17.446881+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-03-23T12:18:17.446882+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-03-23T12:18:17.446882+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-03-23T12:18:17.446883+00:00 app[web.1]:     at Function.Module.runMain (module.js:447:10)
2016-03-23T12:18:17.446884+00:00 app[web.1]:     at startup (node.js:141:18)
2016-03-23T12:18:17.446884+00:00 app[web.1]:     at node.js:933:3
2016-03-23T12:18:17.459164+00:00 app[web.1]: Worker 1 died.. Restarting
2016-03-23T12:18:19.324838+00:00 app[web.1]: /app/node_modules/parse-server/lib/index.js:335
2016-03-23T12:18:19.324875+00:00 app[web.1]:             throw err;
2016-03-23T12:18:19.324878+00:00 app[web.1]:             ^

This is line 52 in the index file:
ParseServer.createLiveQueryServer(httpServer);
