### ISSUE TITLE
2.2.1 breaks createLiveQuery

### ISSUE THREAD

**Issue by bradyhigginbotham** [ParsePlatform/parse-server#1165]
More of fyi, but the recent push for 2.2.1 seems to have broken the last line in index.js:

`ParseServer.createLiveQueryServer(httpServer)
`

That throws the following error when running **npm start**:
`
TypeError: ParseServer.createLiveQueryServer is not a function
    at Object.<anonymous> (/Users/username/Development/workspace/project/index.js:55:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
`

Reverting the parse-server dependency in package.json from "~2.2.0" to "2.2.0" fixes it for now.

**Comment by Darcklion** [comment]
I also have the same issue, but changing the parse-server dependency in package.json from "~2.2.0" to "2.2.0" doesn`t help.

**Comment by wangmengyan95** [comment]
Should be fixed in #1153

**Comment by drew-gross** [comment]
2.2.2 is now on npm

**Comment by bradyhigginbotham** [comment]
Awesome. Keep up the good work, guys!
