### ISSUE TITLE
ReferenceError: Cloud is not defined when using Cloud Code.

### ISSUE THREAD

**Issue by techsd-repo** [ParsePlatform/parse-server#1177]
When I upload Cloud Code to my Parse Server, there is an error which says "Parse.Cloud.define..." is not a function, I did research and removed "Parse." Now the error is: 

```
ReferenceError: Cloud is not defined
2016-03-24T14:33:29.801025+00:00 app[web.1]:     at Object.<anonymous> (/app/cloud/main.js:10:1)
2016-03-24T14:33:29.801026+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-03-24T14:33:29.801027+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-03-24T14:33:29.801027+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-03-24T14:33:29.801028+00:00 app[web.1]:     at Function.Module._load (module.js:314:12)
2016-03-24T14:33:29.801028+00:00 app[web.1]:     at Module.require (module.js:367:17)
2016-03-24T14:33:29.801029+00:00 app[web.1]:     at require (internal/module.js:16:19)
2016-03-24T14:33:29.801030+00:00 app[web.1]:     at new ParseServer (/app/node_modules/parse-server/lib/index.js:196:7)
2016-03-24T14:33:29.801031+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:13:11)
2016-03-24T14:33:29.801031+00:00 app[web.1]:     at Module._compile (module.js:413:34)
 
```

#### Environment Setup
I'm running the Parse Server on Heroku

#### Steps to reproduce
1. Run a Parse Server on Heroku using the "one-click deploy button"
2. Clone the repo and add in a Cloud Code file with a Cloud Code function
3. Push it up to Heroku

Any help would be great, thanks and if more info is needed just ask me. :)

**Comment by drew-gross** [comment]
Can you show us your server version, folder layout, and server initialization code?

**Comment by techsd-repo** [comment]
Server Version: 2.1.0

- Dockerfile
- README.md
- app.son
- app.yaml
- azuredeploy.json
- cloud
     - (Cloud Code files)
- index.js
- jsconfig.json
- node_modules
       - (Node Modules)
- package.json
- scalingo.json

Server Init:
" npm start " on heroku

**Comment by drew-gross** [comment]
Can you try updating to the latest version (2.2.2) please? I can't think of any changes that would affect this issue, but it's always easiest to debug the latest version.

**Comment by techsd-repo** [comment]
I did a fresh install of a Parse Server (latest version) and found that I was still getting the error. :/

**Comment by drew-gross** [comment]
Did you put the `Parse.` back before the `Cloud.define(...)`? That part should definitely be there. If you found some advice somewhere saying to do otherwise, can you let us know where? Maybe we can remove it, as it's incorrect.

**Comment by techsd-repo** [comment]
Wow, I guess that fixed it, I can't seem to find that advice, I'll keep looking. Thanks

**Comment by techsd-repo** [comment]
New Error :/ -> Whenever I call a cloud code function inside my app, it returns the error: Invalid Function. I've tripe-checked the function name and have verified that it exists in code. I just about to switch to Firebase because of the amount of issues I've been having (I rather not switch because it's time consuming).

Parse Server (Heroku) : 2.2.0

Thanks.

**Comment by drew-gross** [comment]
Invalid function means that Parse Server can't see your function. Can you check that you are setting the location of the Cloud Code correctly in your Parser Server configuration?

**Comment by Flixter** [comment]
Hello. I am having the same issue for over 4 days now and i have no idea how to fix it :( This is my setup
in server.js : 
var parseServer = new ParseServer({
  databaseURI: "XXXXXXX",
  cloud: './cloud/main.js',
  appId: "XXXXXX",
  masterKey: "XXXXXXX",
  serverURL: "https://parsetestapi.appspot.com/parse/"
});

and in app.yaml
 CLOUD_PATH: './cloud/main.js'

Please help me  i am desperate :D

**Comment by techsd-repo** [comment]
The cloud code main directory I have set is "/cloud/main.js"

**Comment by drew-gross** [comment]
Based on the folder structure you showed previously, `/cloud/main.js` is not correct. You probably want `__dirname + /cloud/main.js`.

**Comment by techsd-repo** [comment]
@drew-gross  
I have added the "__dirname", but it does not appear to work.

Cloud Code function:
```
Parse.Cloud.define("ps-matchmake_d1_t1_cc", function(request, response) {
```

Parse Server Initialization:
```
var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep $
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Do$
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for quer$
  }
});
```

**Comment by techsd-repo** [comment]
🙄 I put the wrong URL.. I hate to say that.. I'm just having a another problem that the save failed in a function.. It feels like this issue is going to go on forever..

Cloud Code Function:
```
 gamemanager.set("gmuser1", user1);
       gamemanager.save(null, {
         success: function (game) {

          console.log("Saved user " + user1);
   },
         error: function (error) {
           console.log("Save failed with error: " + error);
          return "Save Failed";

   }
   });
```

**Comment by drew-gross** [comment]
What error message do you see?

**Comment by techsd-repo** [comment]
There's no error message that is put out, the message is the console.log("Save failed with error") and there it is not stored in the database.

**Comment by drew-gross** [comment]
`console.log("Save failed with error: " + error);` this line should be printing an error message specific to why this particular save is failing.

**Comment by techsd-repo** [comment]
Oh, the error that is printed out is just [object Object].

**Comment by drew-gross** [comment]
Try this instead: `console.log(error);` that won't coerce your error object to a string, and will print the object directly.

**Comment by techsd-repo** [comment]
Here's the output from it: `ParseObjectSubclass { className: 'gmgames', _objCount: 0, _localId: 'local0' }`

**Comment by drew-gross** [comment]
Thats not what errors usually look like. Can you go into more detail about how you constructed `gamemanager` and also `console.log` it before you save it?

**Comment by techsd-repo** [comment]
`gamemanager`:
```
var GMClass = parse.Object.extend("gmgames");
var gamemanager = new GMClass();
```

console.log:
```
 error: function (error) {
           console.log(error);
```

**Comment by drew-gross** [comment]
Can you also log `user1` and describe how you constructed it?

**Comment by techsd-repo** [comment]
Logging user1 returns:
```
test01
```
How it is constructed:
```
var user1 = request.params.user;
```

**Comment by drew-gross** [comment]
That all seems like it should work. Do you have a `beforeSave` defined for "gmgames" class?

**Comment by techsd-repo** [comment]
No, I do not have a `beforeSave` defined.

**Comment by drew-gross** [comment]
Can you check the server logs using `VERBOSE=1`? Your error object doesn't look like a regular error.

**Comment by techsd-repo** [comment]
Here's a direct output of the request:
```
2016-03-25T17:24:16.816754+00:00 heroku[router]: at=info method=POST path="/parse/functions/ps-matchmake_d1_t1_cc" host=sleepy-chamber-33958.herokuapp.com request_id=6617fe23-9cd8-489a-960e-8b5dcc5bacec fwd="72.231.241.253" dyno=web.1 connect=0ms service=8ms status=200 bytes=496
2016-03-25T17:24:16.847875+00:00 app[web.1]: POST /parse/functions/ps-matchmake_d1_t1_cc { host: 'sleepy-chamber-33958.herokuapp.com',
2016-03-25T17:24:16.847887+00:00 app[web.1]:   connection: 'close',
2016-03-25T17:24:16.847888+00:00 app[web.1]:   'x-parse-client-version': 'i1.12.0',
2016-03-25T17:24:16.847889+00:00 app[web.1]:   accept: '*/*',
2016-03-25T17:24:16.847890+00:00 app[web.1]:   'x-parse-session-token': 'r:22b5f3f055c6697140b9909862618ec5',
2016-03-25T17:24:16.847891+00:00 app[web.1]:   'x-parse-application-id': '[myAppId]',
2016-03-25T17:24:16.847891+00:00 app[web.1]:   'x-parse-client-key': '[myClientKey]',
2016-03-25T17:24:16.847892+00:00 app[web.1]:   'x-parse-installation-id': '63c3092b-1c4d-4f83-affa-022d4bac52f4',
2016-03-25T17:24:16.847893+00:00 app[web.1]:   'x-parse-os-version': '9.3 (13E233)',
2016-03-25T17:24:16.847893+00:00 app[web.1]:   'accept-language': 'en-us',
2016-03-25T17:24:16.847894+00:00 app[web.1]:   'accept-encoding': 'gzip, deflate',
2016-03-25T17:24:16.847895+00:00 app[web.1]:   'content-type': 'application/json; charset=utf-8',
2016-03-25T17:24:16.847895+00:00 app[web.1]:   'user-agent': 'Quizzy/3232016.1 CFNetwork/758.3.15 Darwin/15.4.0',
2016-03-25T17:24:16.847896+00:00 app[web.1]:   'x-parse-app-build-version': '3232016.1',
2016-03-25T17:24:16.847896+00:00 app[web.1]:   'x-parse-app-display-version': '1.2',
2016-03-25T17:24:16.847897+00:00 app[web.1]:   'x-request-id': '6617fe23-9cd8-489a-960e-8b5dcc5bacec',
2016-03-25T17:24:16.847898+00:00 app[web.1]:   'x-forwarded-for': '72.231.241.253',
2016-03-25T17:24:16.847898+00:00 app[web.1]:   'x-forwarded-proto': 'http',
2016-03-25T17:24:16.847899+00:00 app[web.1]:   'x-forwarded-port': '80',
2016-03-25T17:24:16.847900+00:00 app[web.1]:   via: '1.1 vegur',
2016-03-25T17:24:16.847900+00:00 app[web.1]:   'connect-time': '0',
2016-03-25T17:24:16.847901+00:00 app[web.1]:   'x-request-start': '1458926656806',
2016-03-25T17:24:16.847902+00:00 app[web.1]:   'total-route-time': '0',
2016-03-25T17:24:16.847902+00:00 app[web.1]:   'content-length': '17' } {
2016-03-25T17:24:16.847903+00:00 app[web.1]:   "user": "test01"
2016-03-25T17:24:16.847904+00:00 app[web.1]: }
2016-03-25T17:24:16.848327+00:00 app[web.1]: response: {
2016-03-25T17:24:16.848335+00:00 app[web.1]:   "response": {
2016-03-25T17:24:16.848336+00:00 app[web.1]:     "result": "1"
2016-03-25T17:24:16.848336+00:00 app[web.1]:   }
2016-03-25T17:24:16.848337+00:00 app[web.1]: }
```
Note: I've replaced the app id and client key with placeholders.

**Comment by drew-gross** [comment]
Thats the log for your function. What is the log for the save attempt?

**Comment by techsd-repo** [comment]
There appears to be no output for the save, just to be sure "VERBOSE" is an environment variable, right?

**Comment by drew-gross** [comment]
Yep verbose is an environment variable. Can you try executing the same save from your client instead of a cloud function and see if that works, and if not show what errors you get on the client and server?

**Comment by techsd-repo** [comment]
The save to the class does succeed on the client.

**Comment by drew-gross** [comment]
The issue must be somewhere else in your cloud code then. Maybe your are modifying the `Parse` global, or calling `initialize`, or defining your classes differently, or something like that. If the save works on the client, then the bug is somewhere in your code, not in the server.

**Comment by techsd-repo** [comment]
Ok... Thanks for the help.
