### ISSUE TITLE
Error: Cannot find module './logger' 

### ISSUE THREAD

**Issue by yamill** [ParsePlatform/parse-server#1348]
Hi Guys,

I upgraded to Parse-Server 2.2.4 and I'm receiving this error in Heroku. It's not allowing me to start the server. 

```javascript

Apr 03 06:11:23 myparseapp app/web.1:  Error: Cannot find module './logger' 
Apr 03 06:11:23 myparseapp app/web.1:      at Function.Module._resolveFilename (module.js:339:15) 
Apr 03 06:11:23 myparseapp app/web.1:      at Function.Module._load (module.js:290:25) 
Apr 03 06:11:23 myparseapp app/web.1:      at Module.require (module.js:367:17) 
Apr 03 06:11:23 myparseapp app/web.1:      at require (internal/module.js:16:19) 
Apr 03 06:11:23 myparseapp app/web.1:      at Object.<anonymous> (/app/node_modules/parse-server/lib/ParseServer.js:11:15) 
Apr 03 06:11:23 myparseapp app/web.1:      at Module._compile (module.js:413:34) 
Apr 03 06:11:23 myparseapp app/web.1:      at Object.Module._extensions..js (module.js:422:10) 
Apr 03 06:11:23 myparseapp app/web.1:      at Module.load (module.js:357:32) 
Apr 03 06:11:23 myparseapp app/web.1:      at Function.Module._load (module.js:314:12) 
Apr 03 06:11:23 myparseapp app/web.1:      at Module.require (module.js:367:17) 

```

On another note, I am able to start the server on my local machine with no errors.

**Comment by flovilmart** [comment]
how did you use parse-server?

**Comment by yamill** [comment]
This is my app.js:

```javascript
var path = require('path');
var express = require('express');
var hbs = require('hbs');
var ParseServer = require('parse-server').ParseServer;
var S3Adapter = require('parse-server').S3Adapter;
var bodyParser = require('body-parser');
var fetch = require('node-fetch');
var app = express();

// Specify the connection string for your mongodb database
// and the location to your Parse cloud code
var api = new ParseServer({
  databaseURI: 'mongodb://******:******@ds*****.mlab.com:11449/heroku_******',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js', // Provide an absolute path
  appId: 'myparseapp',
  masterKey: 'somespecialkey', // Keep this key secret!
  serverURL: 'https://www.mydomain.com/parse', // Don't forget to change to https if needed
  push: {
    ios: [
      {
        pfx: __dirname + '/dev.p12', // Dev PFX or P12
        bundleId: 'hypurrr',
        production: false // Dev
      },
      {
        pfx: __dirname + '/prod.p12', // Prod PFX or P12
        bundleId: 'hypurrr',
        production: true // Prod
      }
    ]
  },
  filesAdapter: new S3Adapter(
    "****************",
    "****************",
    "myparseapp",
    { directAccess: true }
  )
});

app.use('/', express.static(path.join(__dirname, 'public')));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));

app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'hbs');

app.use('/parse', api);


var port = process.env.PORT || 3001;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server running on port ' + port + '.');
});


```


and my package.json:

```javascript
{
  "name": "parse-server",
  "version": "1.0.0",
  "description": "mydomain.com server",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node app.js"
  },
  "author": "Yamill Vallecillo <yamill@gmail.com> (http://github.com/yamill)",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.15.0",
    "express": "^4.13.4",
    "hbs": "^4.0.0",
    "node-fetch": "^1.3.3",
    "openssl": "^1.1.0",
    "parse": "^1.7.1",
    "parse-image": "^0.1.1",
    "parse-server": "^2.2.4"
  }
}

```

**Comment by flovilmart** [comment]
I seems that heroku is not properly updating your dependencies...

**Comment by yamill** [comment]
Hmmm any tips on how to fix this? :bow:

**Comment by flovilmart** [comment]
not sure.. I'm no expert in heroku deployments.

**Comment by yamill** [comment]
Ok thanks. I will continue researching and get back with a solution.

**Comment by flovilmart** [comment]
did you try that: https://devcenter.heroku.com/articles/nodejs-support#cache-behavior

**Comment by yamill** [comment]
yeah i actually tried that but no luck :disappointed:

**Comment by flovilmart** [comment]
If you try to re-deploy, can you send me the logs? in a gist that's fine

**Comment by yamill** [comment]
Sure here ya go. I appreciate the help!

https://gist.github.com/yamill/3b56ae8915b8fb094e84c1a68cebc98d

**Comment by flovilmart** [comment]
on you local machine the node_modules/parse-server/lib/logger.js exists?

**Comment by yamill** [comment]
yup it's there

**Comment by yamill** [comment]
Aha! I figured it out! Probably a total newbie mistake...I just ended up deleting the **node_modules **directory and deployed the app again and it worked. Looks like Heroku handles the npm install on it's own.

From now on I just added **/node_modules** to my **.gitignore** so that it follows this behavior from now on.

Thanks for your help @flovilmart

**Comment by BakirRabiaSalma** [comment]
I have the same problem i try to reinstall the node_modules but the error persiste
