### ISSUE TITLE
Recent grpc update issue

### ISSUE THREAD

**Issue by alarrosa14** [ParsePlatform/parse-server#1378]
Some module uses grpc. This module was recently updated to 0.13.1 and it's not possible tu run Parse Server with that version.
I get this error when running `npm start`:

```
Error: Cannot find module '/home/ubuntu/parse-server-example/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/parse-server-example/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Adding grpc 0.13.0 to my dependecy list in package.json seem to fix the problem.**

**Comment by flovilmart** [comment]
what version of node are you using?

**Comment by flovilmart** [comment]
Also, can you try:

delete your node_modules folder, and re-run npm install

**Comment by alarrosa14** [comment]
I did this in the wrong guthub repo. This is happenning in parse-server-example repository, my bad... 
Not sure if this is happening here to.

**Comment by flovilmart** [comment]
I'll close it then :)
