### ISSUE TITLE
cannot find SimpleMailgunAdapter after upgrading 2.2.6

### ISSUE THREAD

**Issue by jiawenzhang** [ParsePlatform/parse-server#1442]
After change "parse-server": "~2.2.5" to "parse-server": "~2.2.6" in package json and run

npm install and restart parse server, I keep getting the following error.   

```
at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/opt/wishlist-parse-server/index.js:15:28)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
Error: Cannot find module 'parse-server/lib/Adapters/Email/SimpleMailgunAdapter'
```

**Comment by jiawenzhang** [comment]
And I noticed parse-server/lib/Adapters/Email/SimpleMailgunAdapter.js is gone. It is used to be there in 2.2.5

**Comment by Bragegs** [comment]
try:
    emailAdapter: {
       module: 'parse-server-simple-mailgun-adapter',
       options: {
         fromAddress: 'adress',
         apiKey: 'key',
         domain: 'domain',
       }
     }

**Comment by jiawenzhang** [comment]
@Bragegs that's what I have in my index.js, still the same error

**Comment by jiawenzhang** [comment]
ok, I fixed it.

removing
`var SimpleMailgunAdapter = require('parse-server/lib/Adapters/Email/SimpleMailgunAdapter');`

fixed it. thanks.
