### ISSUE TITLE
Cannot deploy parse server to localhost

### ISSUE THREAD

**Issue by AmbroiseCollon** [ParsePlatform/parse-server#1445]
I use parse-server@2.2.6
I have deployed parse server using heroku button. Now I want to run it locally. And when I run `npm start` locally, i get the following error :

```
> parse-server-example@1.1.0 start /Users/ambroisecollon/Documents/app
> node index.js

module.js:339
    throw err;
    ^

Error: Cannot find module './modules/es6.symbol'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ambroisecollon/Documents/app/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/shim.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Darwin 15.3.0
npm ERR! argh "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! nom  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! parse-server-example@1.1.0 start: `node index.js`
npm ERR! Exit status 1
nom ERR! 
npm ERR! Failed at the parse-server-example@1.1.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and nam installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with nam itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     nam bugs parse-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     nam owner ls parse-server-example
npm ERR! There is likely additional logging output above.
```

**Comment by mikepaggi** [comment]
What version of Node are you running and have your run 'npm install' locally in that parse-server example directory?

**Comment by AmbroiseCollon** [comment]
Node 5.10.1
I did run `npm install`

**Comment by flovilmart** [comment]
Try updating to the latest version of parse-server, and reopen if the issue persist.

**Comment by AmbroiseCollon** [comment]
It works now with latest version. Sorry I did not updated this thread.
