### ISSUE TITLE
Unable to start parse-server using quick start guide

### ISSUE THREAD

**Issue by nooruls143** [ParsePlatform/parse-server#1449]
Hi,

I am using Centos 7 Amazon EC2 instance. I tried to follow the steps in the quick start guide to install and start parse-server. I get the following error:

 ```
yum.repos.d]$ sudo parse-server --appId vYIA9W38ZfCYq3 --masterKey WHqnXKNsG18o6A

/usr/lib/node_modules/parse-server/lib/logger.js:65
  if (!_path2.default.isAbsolute(logsFolder)) {
                      ^
TypeError: Object [object Object] has no method 'isAbsolute'
    at configureLogger (/usr/lib/node_modules/parse-server/lib/logger.js:65:23)
    at Object.<anonymous> (/usr/lib/node_modules/parse-server/lib/logger.js:78:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/parse-server/lib/ParseServer.js:11:15)
    at Module._compile (module.js:456:26)
```

Please help

Thanks,
Noorul

**Comment by flovilmart** [comment]
which version of node are you using?

**Comment by ibrahim132** [comment]
I have the same issue. How i can fix this.
Installed nodejs is `nodejs-0.10.42-4.fc23.x86_64`

**Comment by ibrahim132** [comment]
Fixed by following this tutorial to install nodejs [How to Upgrade Node.js via NPM](http://tecadmin.net/upgrade-nodejs-via-npm/)

**Comment by iksnae** [comment]
i'm seeing this same issue when deploying to openshift.. it's fine local, but when i deploy i get the same error.
<img width="1190" alt="screen shot 2016-05-23 at 8 08 58 pm" src="https://cloud.githubusercontent.com/assets/799271/15491131/87748602-2122-11e6-9eba-9c12946d47e2.png">
