### ISSUE TITLE
issues with running Parse Server with Phusion Passenger on Dreamhost VPS

### ISSUE THREAD

**Issue by mikepaggi** [ParsePlatform/parse-server#149]
I've currently setup a vanilla Parse Server / Express.js(Node) on my Dreamhost VPS with Node.js 5.5.0 and using Phusion Passenger.

When I run locally on my Mac with same environment (though i think i have newer Passenger installed though i don't know how it would be affected by this issue) I get this error and it doesn't happen to me locally.

`/home/USERNAME/DOMAIN/public/node_modules/parse-server/index.js:153
    request(options, (error, response, body) => {
                                             ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/USERNAME/DOMAIN/public/app.js:2:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
`

**Comment by gfosco** [comment]
Are you sure they are using Node 5?  The "=>" syntax is ES6 JavaScript and supported by Node 4.1 and above...

**Comment by mikepaggi** [comment]
Yes that was my first thoughts as maybe it was running a different node version.  I setup nvm set it to use 5.5.0.  Do you think it's using the system version when I'm not ssh'ed into the box?

**Comment by gfosco** [comment]
I'm not sure, maybe you can raise this with Dreamhost support.  Closing since it does not appear to be a problem with parse-server.
