### ISSUE TITLE
parse-server-push-adapter error when sending push

### ISSUE THREAD

**Issue by tylerarnold** [ParsePlatform/parse-server#1634]
I receive the following error: "ERR! parse-server-push-adapter APNS cannot find vaild connection for "
when trying to debug push notifications on a local server environment.  Note that with the same .p12 key /certificate, I can successfully push notifications to APNS and the same iPhone via a php script running locally.

#### Environment Setup
parse server 2.27 running on OSX

#### Steps to reproduce

configure with one installation from app, start server locally with pfx config pointed to .p12 file.
start a APNS push via curl or the parse-dashboard. 

#### Logs/Trace

"verbose: sending push to 1 installations
ERR! parse-server-push-adapter APNS cannot find vaild connection for 768dfdea3b13c3f2ab64dcf3d5fc82e4dd5081189e8d98bf848fa579b848c1a1
/usr/local/lib/node_modules/parse-server/lib/ParseServer.js:329
            throw err;
            ^

Error: mac verify failure
    at Error (native)
    at Object.createSecureContext (_tls_common.js:132:17)
    at Object.TLSSocket._init.ssl.onclienthello.ssl.oncertcb.exports.connect (_tls_wrap.js:972:23)
    at apnSocket (/usr/local/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/lib/socket.js:56:19)
    at Connection.<anonymous> (/usr/local/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/lib/connection.js:199:17)
    at _fulfilled (/usr/local/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:604:44
    at runSingle (/usr/local/lib/node_modules/parse-server/node_modules/parse-server-push-adapter/node_modules/apn/node_modules/q/q.js:137:13)
"

**Comment by flovilmart** [comment]
please open on github.com/parse-server-modules/parse-server-push-adapter

**Comment by tylerarnold** [comment]
will do.
