### ISSUE TITLE
PUSH: error: error while sending push TypeError: type.startsWith is not a function

### ISSUE THREAD

**Issue by shariqkhan1** [ParsePlatform/parse-server#1712]
#### Environment Setup
Parse server: 2.2.7

#### Steps to reproduce
Installed parse server and tried to send push notification and error was shown in the logs

#### Logs/Trace

`error: error while sending push TypeError: type.startsWith is not a function
    at mongoFieldToParseSchemaField (/parse/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoSchemaCollection.js:32:12)
    at /parse/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoSchemaCollection.js:65:22
    at Array.reduce (native)
    at mongoSchemaFieldsToParseSchemaFields (/parse/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoSchemaCollection.js:64:29)
    at mongoSchemaToParseSchema (/parse/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoSchemaCollection.js:91:13)
    at Array.map (native)
    at /parse/node_modules/parse-server/lib/Adapters/Storage/Mongo/MongoSchemaCollection.js:183:24
    at run (/parse/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /parse/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/parse/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)`

**Comment by hramos** [comment]
Can you include more details about how you sent the push, what the payload looks like, etc?

**Comment by shariqkhan1** [comment]
I sent the push using postman. To this URL:

http://192.168.146.160:1337/parse/push

Here is the Payload:

In my mongodb collection, I have added a field for username and I am making the query based on username. I am also sending ReportID and Category as data in my push message.
{
  		"where": {
          "username": "RegeShark"
  		},
        "data": {
          "alert": "Your Report #A1434367039545 changed status to resolved",
          "sound": "default",
          "reportid": "#B1450429923842",
          "category": "FIRST_CATEGORY"
        }
}

**Comment by flovilmart** [comment]
Closing due to lack of activity, please update to latest parse-server version and reopen if the issue persist.

Don't forget to include your current:
- node version
- npm version
- parse-server version
- any relevant logs (VERBOSE=1 will enable verbose logging)
