### ISSUE TITLE
Passing parameters for a find or count query throws error code 105 on parse-server, invalid key name

### ISSUE THREAD

**Issue by doctrineofvoid** [ParsePlatform/parse-server#1829]
Passing parameters for a query is making the code throw and exception on the client side.
I am using dot net sdk v 1.7.0.0.
parse-server version: 2.2.9
mongo-db version:  3.0.6

error message: invalid key name: 0
.net client side exception stack trace:
     at Parse.Internal.ParseCommandRunner.<>c__DisplayClass2.<RunCommandAsync>b__1(Task`1 t)
   at Parse.Internal.InternalExtensions.<>c__DisplayClass1`2.<OnSuccess>b__0(Task t)
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Parse.Internal.InternalExtensions.<>c__DisplayClass7`1.<OnSuccess>b__6(Task t)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BaserlyWebAdmin.BL.ParseController.<GetUsersCount>d__6.MoveNext() in C:\Projects\dotnet\Baserly\BaserlyWebAdmin\BL\ParseController.cs:line 140
I am not sure though if this is a server issue or an sdk issue.

this is the log for the request from the server:

verbose: GET /parse/classes/_User?where=%7B%22%24or%22%3A%5B%7B%22facebookEmail%22%3A%7B%22%24regex%22%3A%22%5C%5CQmaher%5C%5CE%22%7D%7D%2C%7B%22%24or%22%3A%5B%7B%22fullname%22%3A%7B%22%24regex%22%3A%22%5C%5CQmaher%5C%5CE%22%7D%7D%2C%7B%22%24or%22%3A%5B%7B%22address%22%3A%7B%22%24regex%22%3A%22%5C%5CQmaher%5C%5CE%22%7D%7D%2C%7B%22email%22%3A%7B%22%24regex%22%3A%22%5C%5CQmaher%5C%5CE%22%7D%7D%5D%7D%5D%7D%5D%2C%22username%22%3A%7B%22%24ne%22%3A%22amal%40aaaaaaa.com%22%7D%7D&limit=0&count=1 
{ 'x-parse-application-id': '4YJy1QKi1cF66u4BGmTxCqOvSP4iRVX3nBU6gjfh',
 'x-parse-client-version': 'net-netfx1.7.0.0',
 'x-parse-installation-id': '29931453-39de-4696-937e-3267f912a2ad',
 'x-parse-os-version': 'Microsoft Windows NT 10.0.10586.0',
 'x-parse-windows-key': 'f85uzKda0EmWkw6uChTX4hgscov5KB7ajyMLt23B',
 'x-parse-session-token': 'r:56900a853d5095657105a509e3c81c4e',
 'cache-control': 'no-cache',
 host: '192.168.139.150:1343' } {}
verbose: error: code=105, message=invalid key name: 0

**Comment by bohemima** [comment]
The query looks funny

`{"$or":[{"requestStatus":"PENDING"},{"$or":[{"requestStatus":"PENDING"},{"requestStatus":"PENDING"}]}]}`

Can you provide the exact code that creates this error?

**Comment by doctrineofvoid** [comment]
@bohemima  I have edited the log the other example was a bit complicated because it was a merge of 3 queries. Please have a look a the updated error. It is the same issue.

and this is the client query:
public async Task<ParseControllerReturn> GetUsersCount(bool isPro, bool isRegular, bool emailVerified, bool emailUnverified, string searchKey, DateTime? StartDate, DateTime? EndDate, string Language)
        {
            try
            {
                ParseQuery<ParseUser> query = ParseUser.Query;

                

                if ((isPro && !isRegular) || (!isPro && isRegular))
                {
                    if (isPro)
                        query = query.WhereExists("professional_obj");
                    if (isRegular)
                        query = query.WhereDoesNotExist("professional_obj");
                }

                if ((emailVerified && !emailUnverified) || (!emailVerified && emailUnverified))
                {
                    if (emailVerified)
                        query = query.Where(qq => qq.Get<bool>("emailVerified") == true);
                    if (emailUnverified)
                        query = query.Where(qq => qq.Get<bool>("emailVerified") == false);
                }


                if (!string.IsNullOrEmpty(Language))
                {
                    if (Language == "en")
                        query = query.WhereEqualTo("appLanguage", Language);
                    else if (Language == "ar")
                    {
                        query = query.WhereNotEqualTo("appLanguage", "en");
                    }
                }


                if (!String.IsNullOrEmpty(searchKey))
                    query = query.Where(qq => qq.Get<string>("email").Contains(searchKey) || qq.Get<string>("address").Contains(searchKey) || qq.Get<string>("fullname").Contains(searchKey) || qq.Get<string>("facebookEmail").Contains(searchKey));


                query = query.Where(qq => qq.Username != "amal@baserly.com");

                if (StartDate.HasValue)
                    query = query.Where(qq => qq.CreatedAt >= StartDate.Value);

                if (EndDate.HasValue)
                    query = query.Where(qq => qq.CreatedAt <= EndDate.Value);

                int result = await query.CountAsync();

                ParseControllerReturn ret = new ParseControllerReturn();
                ret.hasError = false;
                ret.result = result;

                return ret;
            }
            catch (Exception ex)
            {
                ParseControllerReturn ret = new ParseControllerReturn();
                ret.hasError = true;
                ret.result = null;
                ret.error = ex.ToString();

                return ret;
            }
}

**Comment by flovilmart** [comment]
Closing due to lack of activity, please update to latest parse-server version and reopen if the issue persist.

Don't forget to include your current:
- node version
- npm version
- parse-server version
- any relevant logs (VERBOSE=1 will enable verbose logging)
