### ISSUE TITLE
rest Api and push notification =  Cannot assign to read only property 'deviceType'...

### ISSUE THREAD

**Issue by MattiaConfalonieri** [ParsePlatform/parse-server#1847]
Hi, i have  a problem with rest api and sending push, with cloud code push work, but with rest api don't,

here my code:

`  

 		$alertTitle = "La ricetta del giorno è: \"$nome\"";
    		$riferimento =	$numero;
    		$url3 = 'http://piccole-ricette.herokuapp.com/parse/push';
    		$data = array(
      			'where' => '{"channels": "NotificheValentina"}',
      		  'data' => array(
       		     'alert' => $alertTitle,
          		  'sound' => 'yummy.caf',
    				"cheNotifica"=> "newRecipes",
    				"riferimento"=> $riferimento,
    				"titolo"=> $nome,
    				'badge'=>1,
      		  ),
    		);
    		$_data = json_encode($data);
    		$headers = array(
       		 'X-Parse-Application-Id: ' . $APPLICATION_ID,
           "X-Parse-MASTER-Key: " . $REST_MASTER_KEY,
       		 'Content-Type: application/json',
       		 'Content-Length: ' . strlen($_data)
    		);

        $curl3 = curl_init($url3);
        curl_setopt($curl3, CURLOPT_POST, 1);
        curl_setopt($curl3, CURLOPT_POSTFIELDS, $_data);
        curl_setopt($curl3, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($curl3, CURLOPT_RETURNTRANSFER,1);
        curl_exec($curl3);

    		echo "Notifica inviata";
`

As you can see in the log i receive a Error: unauthorized: Cannot assign to read only property 'deviceType' of {"channels": "NotificheValentina"}

i really don't understand mean...

Anybody can help me please?

- [ •] I've met the prerequisites.
- [• ] I're running the latest version of Parse Server.
- [ •] I've searched through existing issues

**Logs/Trace**

```
error: error while sending push TypeError: Cannot assign to read only property 'deviceType' of {"channels": "NotificheValentina"}
2016-05-23T10:24:07.224218+00:00 app[web.1]:     at badgeUpdate (/app/node_modules/parse-server/lib/Controllers/PushController.js:104:36)
2016-05-23T10:24:07.224219+00:00 app[web.1]:     at /app/node_modules/parse-server/lib/Controllers/PushController.js:120:16
2016-05-23T10:24:07.224220+00:00 app[web.1]:     at run (/app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
2016-05-23T10:24:07.224220+00:00 app[web.1]:     at /app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
2016-05-23T10:24:07.224221+00:00 app[web.1]:     at flush (/app/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
2016-05-23T10:24:07.224221+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-05-23T10:24:07.224222+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by MattiaConfalonieri** [comment]
Anybody can help me please?

**Comment by flovilmart** [comment]
Can you update to latest parse-server version and reopen the issue if it's still occurring?
