### ISSUE TITLE
Wrong protocol message makes LiveQuery server crashed.

### ISSUE THREAD

**Issue by hl4hck** [ParsePlatform/parse-server#1930]
I am developing a mobile game using Unity3D and testing LiveQuery with REST API (HTTP.Request).
LiveQuery works well with REST API.
But when I send wrong protocol message like WebSocket.Send("wrong format"), LiveQuery server crashes.

### Steps to reproduce

- Unity C# Code
	IEnumerator StartConnect () {
		var ws = new HTTP.WebSocket ();

		//This lets the websocket connection work asynchronously.
		StartCoroutine (ws.Dispatcher ());

		//Connect the websocket to the server.
		ws.Connect (url);

		//Wait for the connection to complete.
		yield return ws.Wait();

		//Always check for an exception here!
		if(ws.exception != null) {
			Debug.Log("An exception occured when connecting: " + ws.exception);
		}

		//Display connection status.
		Debug.Log("Connected? : " + ws.connected);

		//If websocket connected succesfully, we can send and receive messages.
		if(ws.connected) {
			//This specified that our OnStringReceived method will be called when a message is received.
			ws.OnTextMessageRecv += OnStringReceived;

			ws.Send("{\"applicationId\" : \"app_id\", \"op\": \"connect\"}");
			
			... Send subscribe message
			
			ws.Send("hello"); <---- crash
		}
	}

	void OnStringReceived(string msg) {
		Debug.Log ("From server -> " + msg);
	}

### Environment Setup

- **Server**
  - parse-server version: 2.2.10
  - Operating System:  Mac OSX 10.11.4
  - Hardware: Intel Core i7 2.7 GHz  64bit
  - Localhost or remote server? Localhost

- **Database**
  - MongoDB version: 3.0.12
  - Storage engine: Default
  - Hardware: Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz
  - Localhost or remote server? Azure Ubuntu 14.04 LTS 64bit

### Logs/Trace
/-----/parse-server/node_modules/parse-server/lib/ParseServer.js:339
            throw err;
            ^
SyntaxError: Unexpected token h
    at Object.parse (native)
    at WebSocket.<anonymous> (/-----/parse-server/node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js:446:26)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.ontext (/-----/parse-server/node_modules/ws/lib/WebSocket.js:841:10)
    at /-----/parse-server/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/-----/parse-server/node_modules/ws/lib/Receiver.js:371:5)
    at /-----/parse-server/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/-----/parse-server/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.opcodes.1.finish (/-----/parse-server/node_modules/ws/lib/Receiver.js:541:12)

**Comment by hramos** [comment]
We're closing this issue due to inactivity. 

If this is a bug you care about that is not getting attention, consider opening a pull request with a fix.
