### ISSUE TITLE
Uncaught internal server error

### ISSUE THREAD

**Issue by otymartin** [ParsePlatform/parse-server#1939]
Describe your issue in as much detail as possible.
I woke up this morning with my app simply not communicating with the database/server. It attempts to make a network call (The activity spinner keeps spinning forever) but nothing happens and no error is logged on the client side.

My server is online and working (Hosted on Google App Engine)

I opened my parse server dashboard and everything is empty as if things were wiped out. No data in the data browser.
<img width="296" alt="screen shot 2016-05-28 at 2 25 31 pm" src="https://cloud.githubusercontent.com/assets/2222881/15629181/34b0bc6c-24e0-11e6-9535-13dd90938b1b.png">

### Steps to reproduce
Go to sleep, wake up and things wont work

#### Expected Results
I expect to see data in my dashboard and my app to connect to the database
#### Actual Outcome

Nothing is happening.

### Environment Setup

- **Server**
  - parse-server version: 2.2.10
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? Google App Engine

- **Database**
  - MongoDB version: 
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server?: mLab

### Logs/Trace

This is the error log i get from parse server dashboard
```javascript
2016-05-27T16:23:43.275Z - Uncaught internal server error. { MongoError: not authorized for query on appName._SCHEMA
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:182:34)
    at Callbacks.emit (/app/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/app/node_modules/mongodb-core/lib/topologies/server.js:358:23)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:292:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:535:20)
  name: 'MongoError',
  message: 'not authorized for query on appName._SCHEMA',
  '$err': 'not authorized for query on appName._SCHEMA',
  code: 13 } MongoError: not authorized for query on appName._SCHEMA
    at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
    at queryCallback (/app/node_modules/mongodb-core/lib/cursor.js:182:34)
    at Callbacks.emit (/app/node_modules/mongodb-core/lib/topologies/server.js:119:3)
    at .messageHandler (/app/node_modules/mongodb-core/lib/topologies/server.js:358:23)
    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:292:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:535:20)
```

**Comment by zzsdeo** [comment]
Yep, I have a same issue.

**Comment by otymartin** [comment]
@zzsdeo What is the problem?

**Comment by zzsdeo** [comment]
I downgraded mongodb driver version to 2.1.18 and now server works about 12 hours without faults.
You can read more here #1855

**Comment by otymartin** [comment]
@zzsdeo I simply redeployed my server to get it back working again. I haven't figured out the problem. Usually i have 3 instances running - When i experienced this issue only 1 instance was running. I was wondering if maybe it was a previously deployed version of my server that app engine scaled down to and my current app lost communication with that version....Just a thought!

**Comment by zzsdeo** [comment]
I run the parse-server in a docker container on one instance. Сontainer restart did not help.
Only restarting instance helped for a while. I tried to redeploy too, but after some time dashboard showed me empty tables again. Only changing version of mongo driver helped to solve the problem.

PS: sorry for my english

**Comment by otymartin** [comment]
how do you change mongo driver version? are you using mlab?

**Comment by zzsdeo** [comment]
No, I'm using an instance vscale.io with ubuntu 14.4.04. On this instance I run separate docker containers with mongo, parse server and dashboard. 
When you install the server, mongo driver is also installed automatically, and for today version of this driver is 2.1.20. 
In my case, to downgrade version I made this:
1. run bash within parse-server container by command - docker exec -it name_of_your_container bash
2. change directory - cd /usr/local/lib/node_modules/parse-server
3. install proper driver - npm install mongodb@2.1.18 --save
4. insure that driver version is 2.1.18 - npm list -g
5. restart instance

**Comment by phonggus** [comment]
Yep, I have a same issue,Help!

**Comment by drew-gross** [comment]
This is probably related to https://github.com/ParsePlatform/parse-server/issues/1855. The solution is to pin your `mongodb` version to `2.1.18`.
