### ISSUE TITLE
Error in authDataManager/facebook.js

### ISSUE THREAD

**Issue by benishak** [ParsePlatform/parse-server#1982]
# Env
Parse 2.2.9 on AWS (CentOS + NGINX)
Node 4.4.2

# Problem

```
SyntaxError: Unexpected token S
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/home/centos/apps/parse-server/source/node_modules/parse-server/lib/authDataManager/facebook.js:40:21)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)
/home/centos/apps/parse-server/source/node_modules/parse-server/lib/ParseServer.js:339
            throw err;
```
 
# Reproduce

As far as I checked the pm2 logs It happens when the user register via facebook

**Comment by drew-gross** [comment]
Can you try upgrading your Parse Server version?

**Comment by hramos** [comment]
We're closing this issue due to inactivity. 

If this is a bug you care about that is not getting attention, consider opening a pull request with a fix.
