### ISSUE TITLE
Config PUT is returning 500 internal server error

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/parse-server#1988]
- [x] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [x] You have filled out every section below. Issues without sufficient information are more likely to be closed.

--

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Create an app
2. Try to add parameters to your Config with the following `curl` command:
```curl
curl -X "PUT" "https://yourparseserver.com/parse/config" \
	-H "Content-Type: application/json; charset=utf-8" \
	-H "X-Parse-Application-Id: YOURAPPID" \
	-H "X-Parse-Master-Key: YOURMASTERKEY" \
	-d "{\"myParam\":\"myValue\"}"
```

#### Expected Results

Update the app config

Server returns 500 internal server error `{"code":1,"message":"Internal server error."}`

[FILL THIS OUT]

### Environment Setup

- **Server**
  - parse-server version: 2.2.11
  - Operating System: Ubuntu
  - Localhost or remote server? Dokku on AWS

- **Database**
  - MongoDB version: 3.0
  - Hardware: AWS EC2 t2.micro
  - Localhost or remote server? AWS

### Logs/Trace

When checking the logs, this is what it returns:

{
    "level": "error",
    "message": "Uncaught internal server error. [TypeError: Cannot convert undefined or null to object] TypeError: Cannot convert undefined or null to object\n    at Function.keys (native)\n    at GlobalConfigRouter.updateGlobalConfig (/app/node_modules/parse-server/lib/Routers/GlobalConfigRouter.js:55:27)\n    at /app/node_modules/parse-server/lib/Routers/GlobalConfigRouter.js:73:23\n    at /app/node_modules/parse-server/lib/PromiseRouter.js:112:22\n    at run (/app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)\n    at /app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28\n    at flush (/app/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)",
    "timestamp": "2016-06-05T10:33:18.175Z"
  }

**Comment by natanrolnik** [comment]
Ooooops, my bad.
Instead of 

`-d "{\"myParam\":\"myValue\"}"`, it should be `-d "{\"params\":{\"myParam\":\"myValue\"}}"`
