### ISSUE TITLE
Internal server error during file upload with Parse-Server Latest version

### ISSUE THREAD

**Issue by guireg** [ParsePlatform/parse-server#2138]
Hi,

I use Parse-server for multiple months, never had any issue except since I updated to the latest version yesterday.

I'm not able anymore to upload files. I use the S3 connector and didn't  change any parameter in AWS or in parse-server index.js file since the update and it returns me an Internal Server error.

I use the latest Parse Javascript SDK (1.6.14) with Parse-Server 2.2.13 . On the server side, it's running on the latest Amazon ElasticBeanstalk version.

I use a test file named permis.jpg to avoid special characters but it doesn't work either. I can put every file I want, even ones that worked before, it's not working.

Thanks for the help !

Here is the complete stack of the error : 

[31merror[39m: Uncaught internal server error. [SyntaxError: Unexpected token ï¿½] SyntaxError: Unexpected token ï¿½
    at Object.parse (native)
    at handleParseHeaders (/var/app/current/node_modules/parse-server/lib/middlewares.js:61:23)
    at Layer.handle [as handle_request] (/var/app/current/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/app/current/node_modules/parse-server/node_modules/express/lib/router/route.js:131:13)
    at /var/app/current/node_modules/parse-server/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/var/app/current/node_modules/parse-server/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
    at done (/var/app/current/node_modules/parse-server/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
    at IncomingMessage.onEnd (/var/app/current/node_modules/parse-server/node_modules/body-parser/node_modules/raw-body/index.js:307:7)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)

**Comment by zeustl** [comment]
This error is easily reproduced by setting bad X-Parse-Apllication-Id in the headers .

Let's say , for example that in your parse server you have the following setup : 

```
var api = new ParseServer({
   ...
  appId: 'awesomeApp',
...
}
``` 

A POST to upload a file like : 
`curl -X POST -H "X-Parse-Application-Id: crashAppID" -H "Content-Type: text/plain" -T "D:\test.txt" http://localhost/parse/files/test.txt` -> will cause the error you mentioned.

**Comment by flovilmart** [comment]
@guireg can you try updating to the latest version and reopen if the issue still persists? Could you also provide the logs when running with VERBOSE=1 DEBUG=express
