### ISSUE TITLE
TypeError: Cannot read property '__type' of null

### ISSUE THREAD

**Issue by doender** [ParsePlatform/parse-server#2189]
### Issue Description

While performing a query through the REST API:

```
curl 'http://$IP:1337/parse/classes/SectionItem' --data-binary '{"where":
{"$relatedTo":{"object" {"__type":"Pointer","className":"Class","objectId":"uAgTxj5kIt"},"key":"items"}},
"include":"<lots and lots of nested classes>"
```

 I get the following response:

```
Uncaught internal server error. [TypeError: Cannot read property '__type' of null] TypeError: Cannot read property '__type' of null
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:778:15)
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:753:32)
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:788:10)
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:788:10)
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:753:32)
    at includePath (/usr/lib/node_modules/parse-server/lib/RestQuery.js:644:18)
    at RestQuery.handleInclude (/usr/lib/node_modules/parse-server/lib/RestQuery.js:625:22)
    at /usr/lib/node_modules/parse-server/lib/RestQuery.js:630:22
    at run (/usr/lib/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/lib/node_modules/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
```

I think this could be due to missing pointers

### Environment Setup

- **Server**
  - parse-server version: 2.2.15
  - Operating System:     Debian 8.5
  - Localhost or remote server?: DigitalOcean

- **Database**
  - MongoDB version: 3.0.11
  - Localhost or remote server?: ObjectRocket

**Comment by doender** [comment]
Please let me know if I need to clarify my bug report

**Comment by flovilmart** [comment]
This maybe fixed by that: https://github.com/ParsePlatform/parse-server/pull/2114

**Comment by doender** [comment]
@flovilmart I just tested this branch, but got the same error message. 
I digged a bit deeper and it happens when having null pointers in an array like so:

`[null, null, {__type: "Pointer", className: "_User", objectId: "luvzg4fRHb"}]`

The expected outcome is that the null pointers remain when included in the query, and the non-null pointers are expanded.

I implemented a naive fix which solved the issue, but I don't know whether it broke any tests as I'm unable to run the test suite:

```
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Server.addListener (events.js:239:17)
    at Server.once (events.js:265:8)
    at Server.close (net.js:1490:12)
    at helper.js:82:12
    at new Promise (/root/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:193:7)
    at reconfigureServer (helper.js:81:10)
    at run (/root/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /root/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/root/parse-server/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)

Error: listen EADDRINUSE :::8378
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1382:5)
    at EventEmitter.listen (/root/parse-server/node_modules/express/lib/application.js:617:24)
    at helper.js:92:22
    at Server.<anonymous> (net.js:1491:9)
    at Server.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1537:8)
    at nextTickCallbackWith1Arg (node.js:431:9)
    at process._tickDomainCallback (node.js:394:17)
```

**Comment by jameslin101** [comment]
I'm getting similar error as well 
`2016-08-03T21:05:28.747016+00:00 app[web.2]: error: Uncaught internal server error. [TypeError: Cannot read property '__type' of null] TypeError: Cannot read property '__type' of null
2016-08-03T21:05:28.747046+00:00 app[web.2]:     at findPointers (/app/node_modules/parse-server/lib/RestQuery.js:778:15)
2016-08-03T21:05:28.747047+00:00 app[web.2]:     at findPointers (/app/node_modules/parse-server/lib/RestQuery.js:753:32)
2016-08-03T21:05:28.747048+00:00 app[web.2]:     at findPointers (/app/node_modules/parse-server/lib/RestQuery.js:788:10)
2016-08-03T21:05:28.747048+00:00 app[web.2]:     at findPointers (/app/node_modules/parse-server/lib/RestQuery.js:753:32)
2016-08-03T21:05:28.747049+00:00 app[web.2]:     at includePath (/app/node_modules/parse-server/lib/RestQuery.js:644:18)
2016-08-03T21:05:28.747050+00:00 app[web.2]:     at RestQuery.handleInclude (/app/node_modules/parse-server/lib/RestQuery.js:625:22)
2016-08-03T21:05:28.747051+00:00 app[web.2]:     at RestQuery.handleInclude (/app/node_modules/parse-server/lib/RestQuery.js:634:17)
2016-08-03T21:05:28.747052+00:00 app[web.2]:     at /app/node_modules/parse-server/lib/RestQuery.js:630:22
2016-08-03T21:05:28.747052+00:00 app[web.2]:     at run (/app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
2016-08-03T21:05:28.747053+00:00 app[web.2]:     at /app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
`

**Comment by jameslin101** [comment]
I've discovered that this error happens when I set an object attribute to nil or null, instead of using unset(:attribute) to empty it out. Crazy tho this causes my entire query (and app) to fail..

**Comment by flovilmart** [comment]
@jameslin101 you're on the right track, Can you run with VERBOSE=1 and reproduce the issue so we have the full trace of request/response?

**Comment by doender** [comment]
Yes, I have this also when, for example,` include`'ing an array with null pointers (in the dashboard this shows as `[null,null]`).

**Comment by flovilmart** [comment]
@jameslin101 I have  a fix but I'm unable to write a test that would make this reproducible.

**Comment by doender** [comment]
@flovilmart I don't get the error when setting a pointer field to null and then retrieving it using `include` as @jameslin101  suggests. I only get it when `include`'ing **arrays** with null pointers.

**Comment by flovilmart** [comment]
@doender I'm on it right now, I have a fix but it strips out the null's from the array, do you need them back or not?

**Comment by doender** [comment]
I think we just implemented the same fix :) 
But I would like to keep the nulls as my app relies on the length of the arrays being consistent... Cannot get that to work just yet through

**Comment by flovilmart** [comment]
Alright, I'll add that :)

**Comment by jameslin101** [comment]
Thanks guys for looking into this! I was away this weekend but can send the
log with verbose=1 later tonight if it will still be helpful

**Comment by flovilmart** [comment]
@doender there's an explicit filter on the null and undefined values https://github.com/ParsePlatform/parse-server/blob/master/src/RestQuery.js#L567 Not sure what we should do.

**Comment by doender** [comment]
Ah, I missed that, thanks! 
I know for sure that the original API did return the null values though...

**Comment by flovilmart** [comment]
and makes that test fail: https://github.com/ParsePlatform/parse-server/blob/master/spec/ParseQuery.spec.js#L1621

**Comment by doender** [comment]
A bit random maybe, but would the test pass if we return null, but not undefined ones?
The rationale would be that there is a difference between invalid pointers and explicit null pointers...

**Comment by flovilmart** [comment]
Yep working well!

**Comment by flovilmart** [comment]
This is gonna be in the next release.

**Comment by doender** [comment]
@flovilmart Sadly I still found a related problem when including nested fields of an array of null pointers. For example, I have an object like `{'list': [null, null, null]}` and then query with include `list.field` I get:

```
error: Uncaught internal server error. [TypeError: Cannot read property 'field' of null] TypeError: Cannot read property 'field' of null
    at findPointers (/usr/lib/node_modules/parse-server/lib/RestQuery.js:810:25)
```

**Comment by flovilmart** [comment]
Alright, that's for nested includes. Can you open a new issue please? This one fixes of 1st level includes
