### ISSUE TITLE
events.js:141  throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by vijay-dadhich09** [ParsePlatform/parse-server#2234]
Hi,

I am getting following error while trying to run following JS code.

============ gulpfile.js ======================
var gulp = require('gulp');
var minify = require('gulp-minify');
gulp.task('default', function(){
	return gulp.src('src/*.js').pipe(minify('')).pipe(gulp.dest('./minified'));
});
=================== Error =================

dluvdadhi53240:usinggulp vdadhi$ gulp
[14:36:50] Using gulpfile /Applications/MAMP/htdocs/node/usinggulp/gulpfile.js
[14:36:50] Starting 'default'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)
    at js_error (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)
    at croak (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2103:9)
    at semicolon (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2123:56)
    at simple_statement (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2314:73)
    at eval (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2183:19)
    at eval (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (/Applications/MAMP/htdocs/node/usinggulp/node_modules/gulp-minify/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2429:20)
dluvdadhi53240:usinggulp vdadhi$

**Comment by flovilmart** [comment]
That seems completely unrelated to parse-server
