### ISSUE TITLE
MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: APP._Installation.$installationId_1  dup key

### ISSUE THREAD

**Issue by felipemobile** [ParsePlatform/parse-server#2270]
Hi, I've successfully migrated our apps to a self hosted parse-server and mongodb instance on Amazon AWS. After the migration I've found this duplicate key error on the _Installation collection. What can I do to fix this issue? Thanks in advance.

### Environment Setup

- **Server**
  - parse-server version: 2.2.12
  - Operating System:     Amazon Linux 
  - Hardware:                   t2.small
  - Remote server:          AWS

- **Database**
  - MongoDB version:  2.6.12
  - Remote server:       AWS

### Logs/Trace
```

{
	"level": "error",
	"message": "Uncaught internal server error. { [MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: APP._Installation.$installationId_1  dup key: { : \"\" }]\n  name: 'MongoError',\n  message: 'insertDocument :: caused by :: 11000 E11000 duplicate key error index: APP._Installation.$installationId_1  dup key: { : \"\" }',\n  driver: true,\n  index: 0,\n  code: 11000,\n  errmsg: 'insertDocument :: caused by :: 11000 E11000 duplicate key error index: APP._Installation.$installationId_1  dup key: { : \"\" }' } MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: APP._Installation.$installationId_1  dup key: { : \"\" }\n    at Function.MongoError.create (/.../node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/error.js:31:11)\n    at toError (/.../node_modules/parse-server/node_modules/mongodb/lib/utils.js:114:22)\n    at /.../node_modules/parse-server/node_modules/mongodb/lib/collection.js:701:67\n    at commandCallback (/.../node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1161:9)\n    at Callbacks.emit (/.../node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)\n    at null.messageHandler (/.../node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:295:23)\n    at Socket.<anonymous> (/.../node_modules/parse-server/node_modules/mongodb/node_modules/mongodb-core/lib/connection/connection.js:285:22)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:153:18)",
	"timestamp": "2016-07-12T23:52:13.980Z"
}
```

**Comment by steven-supersolid** [comment]
installationId is a unique index so duplicate values are not permitted. This is a database setting and so should be true of app code still on parse.com.

In your case, an installation is attempted to be added with an installationId of an empty string. Perhaps your client application is not retrieving or sending the installation id correctly?
