### ISSUE TITLE
502 error log cant find module /lib/cli/parse-server

### ISSUE THREAD

**Issue by TravisDev** [ParsePlatform/parse-server#2330]
I am getting a 502 error and the repo is giving me this when I put it on eb. It does not have a lib folder like it is asking for. Is this something that I am doing wrong or is this a repo problem?
>```
```
 parse-server@2.2.15 start /var/app/current
> node ./bin/parse-server

module.js:327
    throw err;
    ^

Error: Cannot find module '../lib/cli/parse-server'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/app/current/bin/parse-server:3:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

npm ERR! Linux 4.4.14-24.50.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.4.6-linux-x64/bin/npm" "start"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! parse-server@2.2.15 start: `node ./bin/parse-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-server@2.2.15 start script 'node ./bin/parse-server'.
npm ERR! This is most likely a problem with the parse-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/parse-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls parse-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/app/current/npm-debug.log
 
```
```

**Comment by flovilmart** [comment]
Did you install parse-server from source?

**Comment by hramos** [comment]
We're closing this issue due to inactivity. 

If this is a bug you care about that is not getting attention, consider opening a pull request with a fix.
