### ISSUE TITLE
GridStoreAdapter - Error - 2.2.14

### ISSUE THREAD

**Issue by bigdoghung** [ParsePlatform/parse-server#2356]
I have been getting this error below for many months. This is the only error I get. I am trying to save files and when files try to post, it throws the error below. I have seen another user post this before but was closed do to the user not following up.

I started off using GridStoreAdapter, then tried S3Adapter for Amazon S3 and back again trying to get the GridStoreAdapter. 

```
Uncaught internal server error. [TypeError: Cannot read property 'getFileData' of undefined] TypeError: Cannot read property 'getFileData' of undefined
    	at getHandler (/usr/local/lib/node_modules/parse-server/lib/Routers/FilesRouter.js:69:22)
    	at Layer.handle [as handle_request] (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    	at next (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/route.js:131:13)
    	at Route.dispatch (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/route.js:112:3)
    	at Layer.handle [as handle_request] (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    	at /usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/index.js:277:22
    	at param (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/index.js:349:14)
    	at param (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/index.js:365:14)
    	at param (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/index.js:365:14)
    	at Function.process_params (/usr/local/lib/node_modules/parse-server/node_modules/express/lib/router/index.js:410:3)
```

I get this error anytime I try to post an image. And I get the above message in the logs and I get this as well:
{"code":1,"message":"Internal server error."} 

  - parse-server version: 2.2.14
  - Operating System:     Ubuntu 14.04 
  - Remote server? Rackspace Cloud

  - MongoDB version: 3.0.9
  - Storage engine:  mongodb_jumbo_replica_set
  - Remote server:  ObjectRocket

VERBOSE =1 shows the above as well in my environment.

**Comment by hramos** [comment]
Does it still occur in 2.2.17?

**Comment by hramos** [comment]
We're closing this issue due to inactivity. 

If this is a bug you care about that is not getting attention, consider opening a pull request with a fix.
