### ISSUE TITLE
parse-wrapper-0 (err): Unable to listen on port 1337. The port is already in use.

### ISSUE THREAD

**Issue by royherma** [ParsePlatform/parse-server#2445]
My parse sever was working fine, but as of late, it has been acting up as of late. I'm running it on an ubuntu 14.04 with pm2 and npm installed.

As i try to start the server using `using pm2 start ecosystem.json --no-daemon` I get an endless restart flow...

This might be a possible to the restarts :

`16:58:39 PM2 Change detected on path logs/parse-server.info.2016-08-03 for app parse-wrapper - restarting`

and this is my current log:

```
16:58:39 PM2 Change detected on path logs/parse-server.info.2016-08-03 for app parse-wrapper - restarting
16:58:39 PM2 Stopping app:parse-wrapper id:0
16:58:39 PM2 Process with pid 26316 still not killed, retrying...
16:58:39 PM2 Process with pid 26316 still not killed, retrying...
16:58:39 PM2 Process with pid 26316 still not killed, retrying...
16:58:39 PM2 Process with pid 26316 still not killed, retrying...
16:58:39 PM2 Process with pid 26316 still not killed, retrying...
16:58:39 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still not killed, retrying...
16:58:40 PM2 Process with pid 26316 still alive after 1600ms, sending it SIGKILL now...
16:58:40 PM2 App [parse-wrapper] with id [0] and pid [26316], exited with code [0] via signal [SIGKILL]
16:58:41 PM2 Starting execution sequence in -fork mode- for app name:parse-wrapper id:0
16:58:41 PM2 App name:parse-wrapper id:0 online
16:58:43 PM2 Change detected on path logs/parse-server.info.2016-08-03 for app parse-wrapper - restarting
16:58:43 PM2 Stopping app:parse-wrapper id:0
16:58:43 PM2 Process with pid 26338 still not killed, retrying...
16:58:43 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:44 PM2 Process with pid 26338 still not killed, retrying...
16:58:45 PM2 Process with pid 26338 still not killed, retrying...
16:58:45 parse-wrapper-0 appId: FbwFDttuoEpCxEfDzDBANWdVRjacDY2aQt
16:58:45 parse-wrapper-0 masterKey: ***REDACTED***
16:58:45 parse-wrapper-0 port: 8080
16:58:45 parse-wrapper-0 databaseURI: mongodb://***REDACTED***@www.storytimeapp.co:27017/StoryTime?ssl=true
16:58:45 parse-wrapper-0 clientKey: f1HKq8ywC5qoh3DuwZwMUDhPV2Xqa52
16:58:45 parse-wrapper-0 restAPIKey: qtq4iP3XQWFEnUSnlGcW8pJA8dB1fYd6z
16:58:45 PM2 Process with pid 26338 still not killed, retrying...
16:58:45 parse-wrapper-0 cloud: /home/parse/cloud/main.js
16:58:45 parse-wrapper-0 push: [object Object]
16:58:45 parse-wrapper-0 fileKey: 6a2db63d-0d2f-4e16-96e2-703953ac214f
16:58:45 parse-wrapper-0 mountPath: /parse
16:58:45 parse-wrapper-0 maxUploadSize: 20mb
16:58:45 parse-wrapper-0 serverURL: http://localhost:8080/parse
16:58:45 parse-wrapper-0 parse-server running on http://localhost:8080/parse
16:58:45 parse-wrapper-0 Termination signal received. Shutting down.
16:58:45 PM2 App [parse-wrapper] with id [0] and pid [26338], exited with code [0] via signal [SIGINT]
16:58:45 PM2 Starting execution sequence in -fork mode- for app name:parse-wrapper id:0
16:58:45 PM2 App name:parse-wrapper id:0 online
16:58:47 PM2 Change detected on path logs/parse-server.info.2016-08-03 for app parse-wrapper - restarting
16:58:47 PM2 Stopping app:parse-wrapper id:0
16:58:47 PM2 Process with pid 26356 still not killed, retrying...
16:58:47 PM2 Process with pid 26356 still not killed, retrying...
16:58:48 PM2 Process with pid 26356 still not killed, retrying...
16:58:48 PM2 Process with pid 26356 still not killed, retrying...
16:58:48 PM2 Process with pid 26356 still not killed, retrying...
16:58:48 PM2 Process with pid 26356 still not killed, retrying...
16:58:48 PM2 Process with pid 26356 still not killed, retrying...
16:58:48 PM2 Process with pid 26356 still not killed, retrying...
16:58:48 PM2 Process with pid 26356 still not killed, retrying...
16:58:48 PM2 Process with pid 26356 still not killed, retrying...
16:58:48 PM2 Process with pid 26356 still not killed, retrying...
16:58:49 PM2 Process with pid 26356 still not killed, retrying...
16:58:49 PM2 Process with pid 26356 still not killed, retrying...
16:58:49 PM2 Process with pid 26356 still not killed, retrying...
16:58:49 PM2 Process with pid 26356 still not killed, retrying...
16:58:49 PM2 Process with pid 26356 still alive after 1600ms, sending it SIGKILL now...
16:58:49 PM2 App [parse-wrapper] with id [0] and pid [26356], exited with code [0] via signal [SIGKILL]
16:58:49 PM2 Starting execution sequence in -fork mode- for app name:parse-wrapper id:0
16:58:49 PM2 App name:parse-wrapper id:0 online
16:58:52 PM2 Change detected on path logs/parse-server.info.2016-08-03 for app parse-wrapper - restarting
16:58:52 PM2 Stopping app:parse-wrapper id:0
16:58:52 PM2 Process with pid 26374 still not killed, retrying...
16:58:52 PM2 Process with pid 26374 still not killed, retrying...
16:58:52 PM2 Process with pid 26374 still not killed, retrying...
16:58:52 PM2 Process with pid 26374 still not killed, retrying...
16:58:52 PM2 Process with pid 26374 still not killed, retrying...
16:58:53 PM2 Process with pid 26374 still not killed, retrying...
16:58:53 PM2 Process with pid 26374 still not killed, retrying...
16:58:53 PM2 Process with pid 26374 still not killed, retrying...
16:58:53 PM2 Process with pid 26374 still not killed, retrying...
16:58:53 parse-wrapper-0 appId: FbwFDttuoEpCxEfDzDBANWdVRjacDY2aQt
16:58:53 parse-wrapper-0 masterKey: ***REDACTED***
16:58:53 parse-wrapper-0 port: 8080
16:58:53 parse-wrapper-0 databaseURI: mongodb://parse:RuhVrni016!@www.storytimeapp.co:27017/StoryTime?ssl=true
16:58:53 parse-wrapper-0 clientKey: f1HKq8ywC5qoh3DuwZwMUDhPV2Xqa52
16:58:53 parse-wrapper-0 restAPIKey: qtq4iPFEnUSnlGcW8pJA8dB1fYd6z
16:58:53 parse-wrapper-0 cloud: /home/parse/cloud/main.js
16:58:53 parse-wrapper-0 push: [object Object]
16:58:53 parse-wrapper-0 fileKey: 6a2db63d-0d2f-4e16-96e2-703953ac214f
16:58:53 parse-wrapper-0 mountPath: /parse
16:58:53 parse-wrapper-0 maxUploadSize: 20mb
16:58:53 parse-wrapper-0 serverURL: http://localhost:8080/parse
16:58:53 parse-wrapper-0 parse-server running on http://localhost:8080/parse
16:58:53 parse-wrapper-0 Termination signal received. Shutting down.
16:58:53 PM2 Process with pid 26374 still not killed, retrying...
```

**Comment by royherma** [comment]
I tried to kill all processes running on port `1337`, then re-started the parse-server process using `pm2 start ecosystem.json --no-daemon` and this is my current log:

```
15:56:39 PM2 Change detected on path logs/parse-server.info.2016-08-03 for app parse-wrapper - restarting
15:56:39 PM2 Stopping app:parse-wrapper id:0
15:56:39 PM2 App [parse-wrapper] with id [0] and pid [9949], exited with code [0] via signal [SIGINT]
15:56:39 PM2 Starting execution sequence in -fork mode- for app name:parse-wrapper id:0
15:56:39 PM2 App name:parse-wrapper id:0 online
15:56:43 parse-wrapper-0 appId: FbwFDttus57ozEoEpCxEfDzDBANWdVRjacDY2aQt
15:56:43 parse-wrapper-0 masterKey: ***REDACTED***
15:56:43 parse-wrapper-0 port: 1337
15:56:43 parse-wrapper-0 databaseURI: mongodb://parse:RuhVrni016!@www.myappurl.co:27017/myapp?ssl=true
15:56:43 parse-wrapper-0 clientKey: f1H8ywC50yf6123z2dUqoh3DuwZwMUDhPVa52
15:56:43 parse-wrapper-0 restAPIKey: qtq4iPXAs3XN29gq231231QWFEnUSnlGcW8pJA8dB1f6z
15:56:43 parse-wrapper-0 cloud: /home/parse/cloud/main.js
15:56:43 parse-wrapper-0 push: [object Object]
15:56:43 parse-wrapper-0 fileKey: 6a2db63d-023f-4e-96e2-703953ac214f
15:56:43 parse-wrapper-0 mountPath: /parse
15:56:43 parse-wrapper-0 maxUploadSize: 20mb
15:56:43 parse-wrapper-0 serverURL: http://localhost:1337/parse
15:56:43 parse-wrapper-0 parse-server running on http://localhost:1337/parse
15:56:43 parse-wrapper-0 warn: Unable to ensure uniqueness for usernames:  Error: connect ECONNREFUSED 198.199.66.90:27017
15:56:43 parse-wrapper-0     at Object.exports._errnoException (util.js:893:11)
15:56:43 parse-wrapper-0     at exports._exceptionWithHostPort (util.js:916:20)
15:56:43 parse-wrapper-0     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
15:56:43 parse-wrapper-0 warn: Unabled to ensure uniqueness for user email addresses:  Error: connect ECONNREFUSED 198.199.66.90:27017
15:56:43 parse-wrapper-0     at Object.exports._errnoException (util.js:893:11)
15:56:43 parse-wrapper-0     at exports._exceptionWithHostPort (util.js:916:20)
15:56:43 parse-wrapper-0     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1075:14)
15:56:43 PM2 Change detected on path logs/parse-server.info.2016-08-03 for app parse-wrapper - restarting
15:56:43 PM2 Stopping app:parse-wrapper id:0
15:56:43 parse-wrapper-0 Termination signal received. Shutting down.
15:56:43 PM2 App [parse-wrapper] with id [0] and pid [9963], exited with code [0] via signal [SIGINT]
15:56:44 PM2 Starting execution sequence in -fork mode- for app name:parse-wrapper id:0
15:56:44 PM2 App name:parse-wrapper id:0 online
```

**Comment by bohemima** [comment]
Your database connection string is visible in the log output.

The restart is because pm2 detected a change in a file (the log). Check the pm2 documentation for how to disable this / or exclude the directory.

**Comment by TylerBrock** [comment]
The issue is most likely related to @bohemima's discovery. Ensure that pm2 is not watching the directories where mongodb is logging or writing data files.
