### ISSUE TITLE
Separate the Parse Server with the LiveQuery Server

### ISSUE THREAD

**Issue by zuanzuan1992** [ParsePlatform/parse-server#2616]
Here is my code:

```node
var express = require('express');
var ParseServer = require('parse-server').ParseServer;

var app = express();

var httpServer = require('http').createServer(app);
httpServer.listen(2337);

ParseServer.createLiveQueryServer(httpServer, {
  appId: 'appId',
  masterKey: 'masterKey',
  serverURL: 'http://localhost:1337/parse',
  redisURL: 'redis://localhost:6379'
});
```

And its output:

```
/path/to/project/node_modules/.npminstall/parse-server/2.2.18/parse-server/lib/LiveQuery/ParseLiveQueryServer.js:85
    _logger2.default.verbose('Support key pairs', this.keyPairs);
                    ^

TypeError: Cannot read property 'verbose' of undefined
    at new ParseLiveQueryServer (/path/to/project/node_modules/.npminstall/parse-server/2.2.18/parse-server/lib/LiveQuery/ParseLiveQueryServer.js:85:21)
    at Function.createLiveQueryServer (/path/to/project/node_modules/.npminstall/parse-server/2.2.18/parse-server/lib/ParseServer.js:417:14)
    at Object.<anonymous> (/path/to/project/index.js:15:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
```

**Comment by zuanzuan1992** [comment]
I fixed it by create a Parse Server instance.

```node
var express = require('express');
var ParseServer = require('parse-server').ParseServer;

// +++++ BEGIN +++++
new ParseServer({
  appId: '',
  masterKey: '',
  serverURL: '',
});
// +++++ END +++++

var app = express();

var httpServer = require('http').createServer(app);
httpServer.listen(2337);

ParseServer.createLiveQueryServer(httpServer, {
  appId: 'appId',
  masterKey: 'masterKey',
  serverURL: 'http://localhost:1337/parse',
  redisURL: 'redis://localhost:6379'
});
```

And its output:

```
info: Parse LiveQuery Server starts running
```

**Comment by zuanzuan1992** [comment]
The [loggerControllerAdapter](https://github.com/ParsePlatform/parse-server/blob/master/src/ParseServer.js#L162) not set when I create a separate LiveQuery Server.

**Comment by flovilmart** [comment]
I'll work on a fix for that as it's a regression. In the meantime, you can use the workaround. (I was about to suggest the same)

**Comment by zuanzuan1992** [comment]
@flovilmart Thank you.

**Comment by Samigos** [comment]
Hello!

I'm in the same place as you were! I have a Parse Server where I run my app and store my db and I have another one for LiveQuery...

That's where I'm stuck... I've seen Parse's documentation, but it's not much explanatory!
Can someone please tell me why do I need redis and how can I use it?
