### ISSUE TITLE
Option authSource on databaseURI is not honored.

### ISSUE THREAD

**Issue by sunshineo** [ParsePlatform/parse-server#2669]
Describe your issue in as much detail as possible.

If the mongo database has an admin user in the admin database but not the database that parse-server is trying to connect to, parse-server cannot connect.
Normally you specify an authSource on the mongodb url and it works. For example the following works:

```
mongo mongodb://admin:password@localhost:27017/parse?authSource=admin
```

But this does not work:

```
var parse = new ParseServer({
  databaseURI: "mongodb://admin:password@localhost:27017/parse?authSource=admin",
  cloud: 'cloud/main.js',
  appId: config.appId,
  masterKey: process.env.PARSE_MASTER_KEY || '',
  serverURL: config.serverURL,
  liveQuery: {
    classNames: [] // List of classes to support for query subscriptions
  },
  allowClientClassCreation: false
});
```
### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.
1. Create a mongodb locally.
2. Add an admin user in the admin database with password
3. Try use https://github.com/ParsePlatform/parse-server-example to connect to the database by change the databaseURI in the index.js to mongodb://admin:password@localhost:27017/parseLocal?authSource=admin
#### Expected Results

parse-server connect successfully
#### Actual Outcome

An error is shown. The error basically means auth failed with mongodb

```
Parse server instance started. Now serving at http://:::1337
warn: Unable to ensure uniqueness for usernames:  MongoError: failed to connect to server [localhost:27017] on first connect
    at .<anonymous> (/home/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/home/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/home/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
warn: Unable to ensure uniqueness for user email addresses:  MongoError: failed to connect to server [localhost:27017] on first connect
    at .<anonymous> (/home/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/home/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at emit (events.js:191:7)
    at Socket.<anonymous> (/home/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
```
### Environment Setup
- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.0-alpha1 
  - Operating System:     mac
  - Hardware:             mac book pro
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): localhost
- **Database**
  - MongoDB version: 3.2
  - Storage engine:  not sure
  - Hardware:        mac
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): localhost

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? Specifically, the `parse-server` version number would help. This is necessary for people to be able to understand and reproduce the issue being reported.

**Comment by sunshineo** [comment]
@hramos  Added.

**Comment by koustabhdolui** [comment]
I have the exact same issue, when I add the admin. 

However, for me the error persists even if I am not specifying the admin and I am doing
databaseURI: databaseUri || 'mongodb://localhost:27017/dev', which is there in the sample for Parse-server.

warn: Unable to ensure uniqueness for usernames:  MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/home/koustabh/parse-server-example/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/home/koustabh/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at Connection.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/koustabh/parse-server-example/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)
warn: Unable to ensure uniqueness for user email addresses:  MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/home/koustabh/parse-server-example/node_modules/mongodb-core/lib/topologies/server.js:313:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/home/koustabh/parse-server-example/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at Connection.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/home/koustabh/parse-server-example/node_modules/mongodb-core/lib/connection/connection.js:162:49)
    at Socket.g (events.js:286:16)
    at emitOne (events.js:96:13)

**Comment by jftuga** [comment]
I am seeing the same error message.  I have tried both:

parse-server --with-a-bunch-of-options --databaseURI ....

parse-server path/to/config.json

**Comment by sunshineo** [comment]
Thank you @koustabhdolui and @jftuga for confirming the problem. Could you give this problem thumbs up using the icon on the top right conner of the post? Maybe it will help this problem to get noticed.

In the mean time, I avoided the problem by just have the user in the database parse is trying to connect to.

**Comment by flovilmart** [comment]
We're aware of the issue but haven't had time to investigate. 
Can you confirm that this works with the node mongo client that we use? We pass the full URL to it (with à minor tweak to properly encode the credentials).

**Comment by sunshineo** [comment]
@flovilmart Thank you for notice. Sounds like you are saying it could be a problem with the underlying library this project use. I defer to owners of this project or someone who can dive deep.

**Comment by Joematpal** [comment]
Why was this closed? Did we ever get a resolution?

**Comment by flovilmart** [comment]
no resolution so far but it seems the issue is in the mongodb client and not in parse-server itself.

**Comment by flovilmart** [comment]
@sunshineo I've not been able to use the authSource option from the CLI. But I managed to use a separate DB for authentication with:

``` 
mongo "localhost:27017/admin" -u admin -p password --authenticationDatabase test
```

**Comment by flovilmart** [comment]
I've also done some extra testing:

```
// Valid auth source
var server = new ParseServer({
  appId: "hello",
  masterKey: "world",
  serverURL: "http://localhost:1337/parse",
  databaseURI: "mongodb://admin:password@localhost:27017/admin?authSource=test"
});

// OK
2016-12-03T10:08:16.428-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:51416 #21 (1 connection now open)
2016-12-03T10:08:16.434-0500 I NETWORK  [conn21] received client metadata from 127.0.0.1:51416 conn21: { driver: { name: "nodejs", version: "2.2.10" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "16.1.0" }, platform: "Node.js v4.5.0, LE, mongodb-core: 2.0.12" }
2016-12-03T10:08:16.529-0500 I ACCESS   [conn21] Successfully authenticated as principal admin on test
2016-12-03T10:08:16.544-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:51417 #22 (2 connections now open)
2016-12-03T10:08:16.610-0500 I ACCESS   [conn22] Successfully authenticated as principal admin on test
```

Invalid auth source:

```
var server = new ParseServer({
  appId: "hello",
  masterKey: "world",
  serverURL: "http://localhost:1337/parse",
  databaseURI: "mongodb://admin:password@localhost:27017/admin?authSource=admin"
});


2016-12-03T10:08:36.503-0500 I NETWORK  [thread1] connection accepted from 127.0.0.1:51421 #23 (1 connection now open)
2016-12-03T10:08:36.510-0500 I NETWORK  [conn23] received client metadata from 127.0.0.1:51421 conn23: { driver: { name: "nodejs", version: "2.2.10" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "16.1.0" }, platform: "Node.js v4.5.0, LE, mongodb-core: 2.0.12" }
2016-12-03T10:08:36.518-0500 I ACCESS   [conn23] SCRAM-SHA-1 authentication failed for admin on admin from client 127.0.0.1:51421 ; UserNotFound: Could not find user admin@admin
2016-12-03T10:08:36.525-0500 I -        [conn23] end connection 127.0.0.1:51421 (1 connection now open)
```

**Comment by pr0tonion** [comment]
Any updates on this thread? Having the same problem on Digital Ocean, should i downgrade my MongoDB?

**Comment by flovilmart** [comment]
@pr0tonion we're running the latest mongoDB driver, and should be compatible with a variety of mongoDB versions.

**Comment by jftuga** [comment]
@pr0tonion: I did a write up on how I got all of this working, including the Parse dashboard:

https://github.com/jftuga/universe/blob/master/parse_centos7_server_install.md

See the section on:  start_parse_server.sh

Hope this helps!

**Comment by towfiqi** [comment]
Same issue here with Digitalocean and withe parse-example-server...
