### ISSUE TITLE
2.2.22 breaks parse-server-mailgun module

### ISSUE THREAD

**Issue by mman** [ParsePlatform/parse-server#2785]
### Issue Description

I'm running stable version of parse-server with parse-server-mailgun module to send customized welcome and password reset emails. Worked fine since beg of August.

Since yesterday when I updated to the latest 2.2.22 the password reset emails are not being sent and parse server logs the following exception:

Downgrading to 2.2.21 and 2.2.20 does not help.

The password reset emails work great in 2.2.19 which I reverted to get everything back to work.

```
#033[31merror#033[39m: Error generating response. ReferenceError: regeneratorRuntime is not defined
     at MailgunAdapter._sendMail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:134:23)
     at MailgunAdapter.sendPasswordResetEmail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:251:25)
     at /parse/node_modules/parse-server/lib/Controllers/UserController.js:194:26
     at process._tickDomainCallback (internal/process/next_tick.js:129:7) 
 #033[31merror#033[39m: Uncaught internal server error. ReferenceError: regeneratorRuntime is not defined
     at MailgunAdapter._sendMail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:134:23)
     at MailgunAdapter.sendPasswordResetEmail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:251:25)
     at /parse/node_modules/parse-server/lib/Controllers/UserController.js:194:26
     at process._tickDomainCallback (internal/process/next_tick.js:129:7) ReferenceError: regeneratorRuntime is not defined
     at MailgunAdapter._sendMail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:134:23)
     at MailgunAdapter.sendPasswordResetEmail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:251:25)
     at /parse/node_modules/parse-server/lib/Controllers/UserController.js:194:26
     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
 ReferenceError: regeneratorRuntime is not defined
     at MailgunAdapter._sendMail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:134:23)
     at MailgunAdapter.sendPasswordResetEmail (/parse/node_modules/parse-server-mailgun/lib/MailgunAdapter.js:251:25)
     at /parse/node_modules/parse-server/lib/Controllers/UserController.js:194:26
     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
### Steps to reproduce

```
  emailAdapter: {
    module: 'parse-server-mailgun',
    options: {
      fromAddress: 'XXX <xxx@yyy.zzz>',
      domain: 'mg.yyy.zzz',
      apiKey: 'key-XXXXXXXXX',
      templates: {
        passwordResetEmail: {
          subject: 'Password Reset',
          pathPlainText: resolve(__dirname, 'templates/password_reset_email.txt'),
          pathHtml: resolve(__dirname, 'templates/password_reset_email.html'),
          //callback: (user) => { return { firstName: user.get('firstName') }}
          // Now you can use {{firstName}} in your templates 
        },
        verificationEmail: {
          subject: 'Welcome',
          pathPlainText: resolve(__dirname, 'templates/verification_email.txt'),
          pathHtml: resolve(__dirname, 'templates/verification_email.html'),
          //callback: (user) => { return { firstName: user.get('firstName') }}
          // Now you can use {{firstName}} in your templates 
        }
      }
    }
  },

```

#### Expected Results

Password reset email sent.

#### Actual Outcome

Password reset emails not sent, parse-server returning ERROR.

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.2.22

**Comment by flovilmart** [comment]
You should probably open that issue on the parse-server-mailgun repository and notify the owner of this problem. We removed babel polyfill to reduce runtime dependencies.

**Comment by mman** [comment]
I was not sure where to file the bug so I chose both.

Issue reported against parse-server-mailgun as well: https://github.com/sebsylvester/parse-server-mailgun/issues/4
