### ISSUE TITLE
Parse server crashes when accessing the file

### ISSUE THREAD

**Issue by newdev7** [ParsePlatform/parse-server#2796]
My parse server hosted on heroku crashes while accessing file occasionally. From the log it looks like it crashes when the file is access multiple times without interval. 

Any pointers would be appreciated .

```
2016-09-28T05:00:24.807570+00:00 heroku[router]: at=info method=GET path="/parse/files/ID/73bee04a716a9a89263ffbc911bff533_audioData.mp3" host=larynxbot.herokuapp.com request_id=bd4eb3ce-7c76-46d0-a487-745caeea6d43 fwd="IP" dyno=web.1 connect=0ms service=42ms status=206 bytes=553
2016-09-28T05:00:24.816388+00:00 app[web.1]: filename
2016-09-28T05:00:24.820883+00:00 app[web.1]: Range Request
2016-09-28T05:00:25.963889+00:00 app[web.1]: filename
2016-09-28T05:00:25.963971+00:00 app[web.1]: Range Request
2016-09-28T05:00:26.192678+00:00 app[web.1]: filename
2016-09-28T05:00:26.200896+00:00 app[web.1]: /app/node_modules/parse-server/lib/ParseServer.js:408
2016-09-28T05:00:26.200897+00:00 app[web.1]:             throw err;
2016-09-28T05:00:26.200898+00:00 app[web.1]:             ^
2016-09-28T05:00:26.200899+00:00 app[web.1]: 
2016-09-28T05:00:26.200900+00:00 app[web.1]: TypeError: Cannot read property 'copy' of null
2016-09-28T05:00:26.200901+00:00 app[web.1]:     at read (/app/node_modules/parse-server/node_modules/mongodb/lib/gridfs/grid_store.js:810:8)
2016-09-28T05:00:26.200902+00:00 app[web.1]:     at GridStore.read (/app/node_modules/parse-server/node_modules/mongodb/lib/gridfs/grid_store.js:778:44)
2016-09-28T05:00:26.200902+00:00 app[web.1]:     at read (/app/node_modules/parse-server/node_modules/mongodb/lib/gridfs/grid_store.js:1730:13)
2016-09-28T05:00:26.200903+00:00 app[web.1]:     at GridStoreStream._read (/app/node_modules/parse-server/node_modules/mongodb/lib/gridfs/grid_store.js:1760:5)
2016-09-28T05:00:26.200904+00:00 app[web.1]:     at GridStoreStream.Readable.read (_stream_readable.js:348:10)
2016-09-28T05:00:26.200905+00:00 app[web.1]:     at resume_ (_stream_readable.js:737:12)
2016-09-28T05:00:26.200908+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-09-28T05:00:26.200908+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
2016-09-28T05:00:26.186141+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/parse/files/ID/73bee04a716a9a89263ffbc911bff533_audioData.mp3" host=larynxbot.herokuapp.com request_id=c64cd3e1-04eb-4e33-857e-5239b6b7072b fwd="IP" dyno=web.1 connect=0ms service=267ms status=503 bytes=0
2016-09-28T05:00:26.177009+00:00 heroku[router]: at=info method=GET path="/parse/files/ID/73bee04a716a9a89263ffbc911bff533_audioData.mp3" host=larynxbot.herokuapp.com request_id=07f04280-4405-40e3-b267-96597a8589f5 fwd="IP" dyno=web.1 connect=0ms service=251ms status=200 bytes=67043
2016-09-28T05:00:26.294667+00:00 heroku[web.1]: Process exited with status 7
2016-09-28T05:00:26.289363+00:00 heroku[web.1]: State changed from up to crashed
```

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
