### ISSUE TITLE
Help Configuring Parse-Server with HTTPS in Express

### ISSUE THREAD

**Issue by jried31** [ParsePlatform/parse-server#2814]
Running Express.js + Parse Server and trying to configure HTTPS on the Parse API route with the 'https' JS library.

Code Snippit:
var https = require('https');
....
https.createServer(config.certificate,app).listen(port,function() {
    console.log('parse-server-example running on port ' + port + '.');
});
// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(https);
---- END SNIPPIT-----

Steps to recreate:
1. Install the proper libs 
Using: Node (4.5), https (1.0.0)

2. Run "node index.js"

#### Expected Results

Server should start with no problems running on an HTTPS port
https://mydomainhere:4444/parse

#### Actual Outcome

~/parse/node_modules/parse-server/lib/ParseServer.js:401
            throw err;
            ^
TypeError: this._server.once is not a function
    at new WebSocketServer (~/parse/node_modules/parse-server/node_modules/ws/lib/WebSocketServer.js:78:18)
    at new ParseWebSocketServer (~/parse/node_modules/parse-server/lib/LiveQuery/ParseWebSocketServer.js:26:13)
    at new ParseLiveQueryServer (~/parse/node_modules/parse-server/lib/LiveQuery/ParseLiveQueryServer.js:103:33)
    at Function.createLiveQueryServer (~/parse/node_modules/parse-server/lib/ParseServer.js:429:14)
    at Object.<anonymous> (~/parse/parse.js:63:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)

### Environment Setup
Using: Node (4.5), https (1.0.0), parse-server ( "2.2.22"), Linux Centos

**Comment by jried31** [comment]
Ended up using NGINX as the solution to my problem, however would you consider extending compatibility with the HTTPS library?
