### ISSUE TITLE
attrs.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by haydenbleasel** [ParsePlatform/parse-server#2949]
Trying to save a simple object:

```
const object = new (Parse.Object.extend('Thingy'))();
object.save(properties).then((obj) => callback(null, obj), callback);
```

Very simple, works throughout the rest of my application but when using the following JSON object (an inbound SendGrid hook as the properties:

```
{
  dkim: '{@gmail.com : pass}',
  to: 'abc@y.com',
  html: '<div dir="ltr">Testing</div>\n',
  from: 'Hayden Bleasel <me@gmail.com>',
  text: 'tanasdpo\n',
  sender_ip: '1.2.3.4',
  envelope: { to: [ 'abc@y.com' ], from: 'me@gmail.com' },
  attachments: '0',
  subject: 'test',
  charsets: { to: 'UTF-8', html: 'UTF-8', subject: 'UTF-8', from: 'UTF-8', text: 'UTF-8' },
  SPF: 'pass',
  files: [],
  user: ParseObjectSubclass { className: '_User', _objCount: 0, id: 'xxxxxxxx' }
}
```

It breaks and results in this error:

```
/Users/haydenbleasel/Documents/Projects/test/node_modules/parse-server/lib/ParseServer.js:425
            throw err;
            ^

TypeError: attrs.hasOwnProperty is not a function
    at ParseObjectSubclass.validate (/Users/haydenbleasel/Documents/Projects/test/node_modules/parse/lib/node/ParseObject.js:947:17)
    at ParseObjectSubclass.save (/Users/haydenbleasel/Documents/Projects/test/node_modules/parse/lib/node/ParseObject.js:1131:31)
```

The function works if I substitute the properties with `{ foo: 'bar' }` so I can only guess that one of those properties isn't agreeing with Parse-Server but they're all strings, objects or arrays. It's not the User pointer being weird, tried removing that but it still breaks.

Running Parse-Server 2.2.23, Node 6.2.1 on OSX 10.10.5 (Yosemite).

**Comment by haydenbleasel** [comment]
Update:

Turns out sometimes objects may not have Object.prototype as its prototype (???) So, checked out the function that was throwing a hissy:

```
/Users/haydenbleasel/Documents/Projects/test/node_modules/parse/lib/node/ParseObject.js:947:17
```

and found the line:

```
if (attrs.hasOwnProperty('ACL') && !(attrs.ACL instanceof _ParseACL2['default'])) { ...
```

swapping it out with this fixes it:

```
if (Object.prototype.hasOwnProperty.call(attrs, 'ACL') && !(attrs.ACL instanceof _ParseACL2['default'])) {
```

That was weird. I'll PR soon this unless someone beats me to it.

**Comment by haydenbleasel** [comment]
Closing in favour of the PR above.
