### ISSUE TITLE
Push Error on Heroku

### ISSUE THREAD

**Issue by adammlevy** [ParsePlatform/parse-server#2966]
- [x ] You've met the prerequisites: https://github.com/ParsePlatform/parse-server/wiki/Parse-Server-Guide#prerequisites.

- [x ] You're running the latest version of Parse Server: https://github.com/ParsePlatform/parse-server/releases

- [x ] You've searched through existing issues: https://github.com/ParsePlatform/Parse-Server/issues?utf8=%E2%9C%93&q=is%3Aissue Chances are that your issue has been reported or resolved before.

- [x ] You have filled out every section below. Issues without sufficient information are more likely to be closed.

### Issue Description

I am getting the following error while trying to perform a push notification from the Parse dashboard and cloud code:

2016-10-30T17:47:23.790410+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/parse/push" host=carr-dev.herokuapp.com request_id=f7c6365d-ed8e-464c-8af8-9cdca38a46f0 fwd="69.42.6.159" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0
2016-10-30T17:47:42.601872+00:00 app[web.1]: [32minfo[39m: warning: error while sending push MongoError: quota exceeded
2016-10-30T17:47:42.601883+00:00 app[web.1]:     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2016-10-30T17:47:42.601885+00:00 app[web.1]:     at toError (/app/node_modules/mongodb/lib/utils.js:114:22)
2016-10-30T17:47:42.601886+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/collection.js:736:67
2016-10-30T17:47:42.601886+00:00 app[web.1]:     at /app/node_modules/mongodb-core/lib/connection/pool.js:436:18
2016-10-30T17:47:42.601887+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-10-30T17:47:42.601888+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:122:9) 

### Steps to reproduce

1. Launch parse dashboard
2. Tap over to push section
3. Send test push

#### Expected Results

Push notification is sent

#### Actual Outcome

Push notification is not sent and above error is reported

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : [2.2.22]
  - Operating System:     [FILL THIS OUT]
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): [Heroku Hobby Dyno]

- **Database**
  - MongoDB version: [3.2.10]
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): [mLab - Sandbox]

### Logs/Trace

You can turn on additional logging by configuring VERBOSE=1 in your environment.

2016-10-30T17:47:23.790410+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/parse/push" host=carr-dev.herokuapp.com request_id=f7c6365d-ed8e-464c-8af8-9cdca38a46f0 fwd="69.42.6.159" dyno=web.1 connect=1ms service=30001ms status=503 bytes=0
2016-10-30T17:47:42.601872+00:00 app[web.1]: [32minfo[39m: warning: error while sending push MongoError: quota exceeded
2016-10-30T17:47:42.601883+00:00 app[web.1]:     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2016-10-30T17:47:42.601885+00:00 app[web.1]:     at toError (/app/node_modules/mongodb/lib/utils.js:114:22)
2016-10-30T17:47:42.601886+00:00 app[web.1]:     at /app/node_modules/mongodb/lib/collection.js:736:67
2016-10-30T17:47:42.601886+00:00 app[web.1]:     at /app/node_modules/mongodb-core/lib/connection/pool.js:436:18
2016-10-30T17:47:42.601887+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:67:7)
2016-10-30T17:47:42.601888+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:122:9)

**Comment by flovilmart** [comment]
This is an error with your database, not related to parse-server, by doing a quick google search, there are many results like:

https://encrypted.google.com/search?hl=fr&q=MongoError%3A%20quota%20exceeded

**Comment by adammlevy** [comment]
Thanks for the super quick response! I couldn't quite understand why I was receiving a db error while sending a push but turns out my db was full which was preventing the push from being sent. Looks like I'll have to upgrade my plan.
