### ISSUE TITLE
Post-migration: an error message thrown "Tried to encode an unsaved file" with saving a File object

### ISSUE THREAD

**Issue by grassland-curing-cfa** [ParsePlatform/parse-server#2998]
Describe your issue in as much detail as possible.

I have done migrating my app from Parse to mLab + Heroku. The error here only occurred after the migration.

I have a table with a File column "UploadedFile". The ParseServer saves the actual file to my S3 bucket.

I use Python and REST api to create a new record and attach the saved File (on S3) to the "UploadedFile" column.

Here is my Python code.
```
fileFullPath = {path to an actual PDF file on local computer}
connection = httplib.HTTPSConnection(env.PARSE_DOMAIN, 443)
			connection.connect()
			print "Connection to PARSE Server [" + env.PARSE_DOMAIN + "] established ... ..."
		
			connection.request('POST', '/' + env.PARSE_MOUNT + '/files/' + env.PARSE_SINGLEFDI_FILE_NAME, open(fileFullPath, 'rb').read(), {
				"X-Parse-Application-Id": env.X_Parse_APP_ID,
				"X-Parse-REST-API-Key": env.X_Parse_REST_API_Key,
				"Content-Type": "application/pdf"
			})
			result = json.loads(connection.getresponse().read())
			print json.dumps(result, indent=4)
			
			if ('url' in result) and ('name' in result):
				uploadedPdfUrl = result["url"]
				uploadedPdfName = result["name"]
				print "* Uploaded pdf url: " + uploadedPdfUrl
				print "* Uploaded pdf name: " + **uploadedPdfName**

				time.sleep(5)
				connection.connect()
				connection.request('POST', '/' + env.PARSE_MOUNT + '/classes/' + env.PARSE_SFDI_UPLOADED_CLASS, json.dumps({
					"UploadedFile": {
						"name": **uploadedPdfName**,
						"__type": "File"
					},
					"UploadedFileUrl": uploadedPdfUrl
				}), {
					"X-Parse-Application-Id": env.X_Parse_APP_ID,
					"X-Parse-REST-API-Key": env.X_Parse_REST_API_Key,
					"Content-Type": "application/json"
				})  # This is where the error message was thrown
				result2 = json.loads(connection.getresponse().read())
				print json.dumps(result2, indent=4)
				
				# Upload was succeesful
				if ('createdAt' in result2):
					upload_file_result = True;
			
			connection.close()
			break
```
The error message from the Heroku log is:
```
[31merror[39m: Error generating response. [Error: Tried to encode an unsaved file.] 
2016-11-03T06:01:18.858591+00:00 app[web.1]: [31merror[39m: Uncaught internal server error. [Error: Tried to encode an unsaved file.] Error: Tried to encode an unsaved file.
2016-11-03T06:01:18.858593+00:00 app[web.1]:     at encode (/app/node_modules/parse-server/node_modules/parse/lib/node/encode.js:75:13)
2016-11-03T06:01:18.858594+00:00 app[web.1]:     at exports.default (/app/node_modules/parse-server/node_modules/parse/lib/node/encode.js:16:10)
2016-11-03T06:01:18.858595+00:00 app[web.1]:     at ParseObject.value (/app/node_modules/parse-server/node_modules/parse/lib/node/ParseObject.js:496:45)
2016-11-03T06:01:18.858595+00:00 app[web.1]:     at /app/node_modules/parse-server/lib/triggers.js:371:75
2016-11-03T06:01:18.858596+00:00 app[web.1]:     at Object.maybeRunTrigger (/app/node_modules/parse-server/lib/triggers.js:348:10)
2016-11-03T06:01:18.858597+00:00 app[web.1]:     at RestWrite.runAfterTrigger (/app/node_modules/parse-server/lib/RestWrite.js:887:19)
2016-11-03T06:01:18.858598+00:00 app[web.1]:     at /app/node_modules/parse-server/lib/RestWrite.js:107:18
2016-11-03T06:01:18.858599+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```
The interesting thing is that the file was actually successfully saved to S3 and I could see from the Dashboard that a new record was successfully created in the table with the File column populated with the correct file name. When I clicked on the File field for the record, it opened a new browser tab and showed the correct PDF file.

By the way, the same Python code worked perfectly before migrated to mLab + Heroku. No such an error message was thrown.

### Steps to reproduce

Please include a detailed list of steps that reproduce the issue. Include curl commands when applicable.

1. Configure your ParseServer to use S3 for file storage
2. Create a new table with a File type column
3. Upload a PDF file to S3 and get the returned file name generated by S3
4. Create a new record on the table and save the file name in the File column.

#### Expected Results

[FILL THIS OUT]

#### Actual Outcome

[FILL THIS OUT]

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 
 ```
       ├── cors@2.8.1
       ├── express@4.11.2
       ├── kerberos@0.0.21
       ├── mailgun-js@0.7.13
       ├── moment@2.15.2
       ├── parse@1.8.5
       ├── parse-server@2.2.23
       └── underscore@1.8.3
```

  - Operating System:     Linux
  - Hardware:             [FILL THIS OUT]
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Heroku

- **Database**
  - MongoDB version: 3.2
  - Storage engine:  [FILL THIS OUT]
  - Hardware:        [FILL THIS OUT]
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): mLab

**Comment by grassland-curing-cfa** [comment]
This is a known issue with beforeSave and afterSave triggers. Had to remove the trigger functions to make upload work.
