### ISSUE TITLE
Unable to get postgres tests to pass on 2.2.24

### ISSUE THREAD

**Issue by alexblack** [ParsePlatform/parse-server#3021]
I'm trying to get Postgres tests to pass locally on `2.2.24` so I can run them against changes for a PR.  I imagine I've got something setup wrong with my environment, I could use some assistance figuring this out, thanks!

Script I'm using to execute the tests:
```
#!/bin/sh
dropdb parse_server_postgres_adapter_test_database
psql -c 'create database parse_server_postgres_adapter_test_database;' -U postgres
psql -c 'CREATE EXTENSION postgis;' -U postgres -d parse_server_postgres_adapter_test_database
psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d parse_server_postgres_adapter_test_database
export PARSE_SERVER_TEST_DB=postgres
export CODE_COVERAGE=1
export PARSE_SERVER_TEST_TIMEOUT=20000
export COVERAGE_OPTION='./node_modules/.bin/istanbul cover'
echo "node --version"
node --version
echo "psql --version"
psql --version
git checkout 5c4806ba6d7311bc83d135ee75388cf67cf4decc
npm run build
npm test
```

Test results:

```
(ddc) Alexs-MacBook-Pro:parse-server alex$ ./test.sh
CREATE DATABASE
CREATE EXTENSION
CREATE EXTENSION
node --version
v4.4.7
psql --version
psql (PostgreSQL) 9.5.3
Note: checking out '5c4806ba6d7311bc83d135ee75388cf67cf4decc'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 5c4806b... Changelog 2.2.24 (#2976)

> parse-server@2.2.24 build /Users/alex/dev/parse/parse-server
> babel src/ -d lib/

src/AccountLockout.js -> lib/AccountLockout.js
src/Adapters/AdapterLoader.js -> lib/Adapters/AdapterLoader.js
src/Adapters/Analytics/AnalyticsAdapter.js -> lib/Adapters/Analytics/AnalyticsAdapter.js
src/Adapters/Cache/CacheAdapter.js -> lib/Adapters/Cache/CacheAdapter.js
src/Adapters/Cache/InMemoryCache.js -> lib/Adapters/Cache/InMemoryCache.js
src/Adapters/Cache/InMemoryCacheAdapter.js -> lib/Adapters/Cache/InMemoryCacheAdapter.js
src/Adapters/Cache/NullCacheAdapter.js -> lib/Adapters/Cache/NullCacheAdapter.js
src/Adapters/Cache/RedisCacheAdapter.js -> lib/Adapters/Cache/RedisCacheAdapter.js
src/Adapters/Email/MailAdapter.js -> lib/Adapters/Email/MailAdapter.js
src/Adapters/Files/FilesAdapter.js -> lib/Adapters/Files/FilesAdapter.js
src/Adapters/Files/GridStoreAdapter.js -> lib/Adapters/Files/GridStoreAdapter.js
src/Adapters/Logger/LoggerAdapter.js -> lib/Adapters/Logger/LoggerAdapter.js
src/Adapters/Logger/WinstonLogger.js -> lib/Adapters/Logger/WinstonLogger.js
src/Adapters/Logger/WinstonLoggerAdapter.js -> lib/Adapters/Logger/WinstonLoggerAdapter.js
src/Adapters/PubSub/EventEmitterPubSub.js -> lib/Adapters/PubSub/EventEmitterPubSub.js
src/Adapters/PubSub/RedisPubSub.js -> lib/Adapters/PubSub/RedisPubSub.js
src/Adapters/Push/PushAdapter.js -> lib/Adapters/Push/PushAdapter.js
src/Adapters/Storage/Mongo/MongoCollection.js -> lib/Adapters/Storage/Mongo/MongoCollection.js
src/Adapters/Storage/Mongo/MongoSchemaCollection.js -> lib/Adapters/Storage/Mongo/MongoSchemaCollection.js
src/Adapters/Storage/Mongo/MongoStorageAdapter.js -> lib/Adapters/Storage/Mongo/MongoStorageAdapter.js
src/Adapters/Storage/Mongo/MongoTransform.js -> lib/Adapters/Storage/Mongo/MongoTransform.js
src/Adapters/Storage/Postgres/PostgresClient.js -> lib/Adapters/Storage/Postgres/PostgresClient.js
src/Adapters/Storage/Postgres/PostgresConfigParser.js -> lib/Adapters/Storage/Postgres/PostgresConfigParser.js
src/Adapters/Storage/Postgres/PostgresStorageAdapter.js -> lib/Adapters/Storage/Postgres/PostgresStorageAdapter.js
src/Auth.js -> lib/Auth.js
src/ClientSDK.js -> lib/ClientSDK.js
src/Config.js -> lib/Config.js
src/Controllers/AdaptableController.js -> lib/Controllers/AdaptableController.js
src/Controllers/AnalyticsController.js -> lib/Controllers/AnalyticsController.js
src/Controllers/CacheController.js -> lib/Controllers/CacheController.js
src/Controllers/DatabaseController.js -> lib/Controllers/DatabaseController.js
src/Controllers/FilesController.js -> lib/Controllers/FilesController.js
src/Controllers/HooksController.js -> lib/Controllers/HooksController.js
src/Controllers/LiveQueryController.js -> lib/Controllers/LiveQueryController.js
src/Controllers/LoggerController.js -> lib/Controllers/LoggerController.js
src/Controllers/PushController.js -> lib/Controllers/PushController.js
src/Controllers/SchemaCache.js -> lib/Controllers/SchemaCache.js
src/Controllers/SchemaController.js -> lib/Controllers/SchemaController.js
src/Controllers/UserController.js -> lib/Controllers/UserController.js
src/LiveQuery/Client.js -> lib/LiveQuery/Client.js
src/LiveQuery/Id.js -> lib/LiveQuery/Id.js
src/LiveQuery/ParseCloudCodePublisher.js -> lib/LiveQuery/ParseCloudCodePublisher.js
src/LiveQuery/ParseLiveQueryServer.js -> lib/LiveQuery/ParseLiveQueryServer.js
src/LiveQuery/ParsePubSub.js -> lib/LiveQuery/ParsePubSub.js
src/LiveQuery/ParseWebSocketServer.js -> lib/LiveQuery/ParseWebSocketServer.js
src/LiveQuery/QueryTools.js -> lib/LiveQuery/QueryTools.js
src/LiveQuery/RequestSchema.js -> lib/LiveQuery/RequestSchema.js
src/LiveQuery/SessionTokenCache.js -> lib/LiveQuery/SessionTokenCache.js
src/LiveQuery/Subscription.js -> lib/LiveQuery/Subscription.js
src/LiveQuery/equalObjects.js -> lib/LiveQuery/equalObjects.js
src/ParseServer.js -> lib/ParseServer.js
src/ParseServerRESTController.js -> lib/ParseServerRESTController.js
src/PromiseRouter.js -> lib/PromiseRouter.js
src/RestQuery.js -> lib/RestQuery.js
src/RestWrite.js -> lib/RestWrite.js
src/Routers/AnalyticsRouter.js -> lib/Routers/AnalyticsRouter.js
src/Routers/ClassesRouter.js -> lib/Routers/ClassesRouter.js
src/Routers/CloudCodeRouter.js -> lib/Routers/CloudCodeRouter.js
src/Routers/FeaturesRouter.js -> lib/Routers/FeaturesRouter.js
src/Routers/FilesRouter.js -> lib/Routers/FilesRouter.js
src/Routers/FunctionsRouter.js -> lib/Routers/FunctionsRouter.js
src/Routers/GlobalConfigRouter.js -> lib/Routers/GlobalConfigRouter.js
src/Routers/HooksRouter.js -> lib/Routers/HooksRouter.js
src/Routers/IAPValidationRouter.js -> lib/Routers/IAPValidationRouter.js
src/Routers/InstallationsRouter.js -> lib/Routers/InstallationsRouter.js
src/Routers/LogsRouter.js -> lib/Routers/LogsRouter.js
src/Routers/PublicAPIRouter.js -> lib/Routers/PublicAPIRouter.js
src/Routers/PurgeRouter.js -> lib/Routers/PurgeRouter.js
src/Routers/PushRouter.js -> lib/Routers/PushRouter.js
src/Routers/RolesRouter.js -> lib/Routers/RolesRouter.js
src/Routers/SchemasRouter.js -> lib/Routers/SchemasRouter.js
src/Routers/SessionsRouter.js -> lib/Routers/SessionsRouter.js
src/Routers/UsersRouter.js -> lib/Routers/UsersRouter.js
src/StatusHandler.js -> lib/StatusHandler.js
src/TestUtils.js -> lib/TestUtils.js
src/authDataManager/OAuth1Client.js -> lib/authDataManager/OAuth1Client.js
src/authDataManager/facebook.js -> lib/authDataManager/facebook.js
src/authDataManager/github.js -> lib/authDataManager/github.js
src/authDataManager/google.js -> lib/authDataManager/google.js
src/authDataManager/index.js -> lib/authDataManager/index.js
src/authDataManager/instagram.js -> lib/authDataManager/instagram.js
src/authDataManager/janraincapture.js -> lib/authDataManager/janraincapture.js
src/authDataManager/janrainengage.js -> lib/authDataManager/janrainengage.js
src/authDataManager/linkedin.js -> lib/authDataManager/linkedin.js
src/authDataManager/meetup.js -> lib/authDataManager/meetup.js
src/authDataManager/spotify.js -> lib/authDataManager/spotify.js
src/authDataManager/twitter.js -> lib/authDataManager/twitter.js
src/authDataManager/vkontakte.js -> lib/authDataManager/vkontakte.js
src/batch.js -> lib/batch.js
src/cache.js -> lib/cache.js
src/cli/definitions/parse-live-query-server.js -> lib/cli/definitions/parse-live-query-server.js
src/cli/definitions/parse-server.js -> lib/cli/definitions/parse-server.js
src/cli/parse-live-query-server.js -> lib/cli/parse-live-query-server.js
src/cli/parse-server.js -> lib/cli/parse-server.js
src/cli/utils/commander.js -> lib/cli/utils/commander.js
src/cli/utils/parsers.js -> lib/cli/utils/parsers.js
src/cli/utils/runner.js -> lib/cli/utils/runner.js
src/cloud-code/HTTPResponse.js -> lib/cloud-code/HTTPResponse.js
src/cloud-code/Parse.Cloud.js -> lib/cloud-code/Parse.Cloud.js
src/cloud-code/httpRequest.js -> lib/cloud-code/httpRequest.js
src/cryptoUtils.js -> lib/cryptoUtils.js
src/defaults.js -> lib/defaults.js
src/deprecated.js -> lib/deprecated.js
src/index.js -> lib/index.js
src/logger.js -> lib/logger.js
src/middlewares.js -> lib/middlewares.js
src/password.js -> lib/password.js
src/requiredParameter.js -> lib/requiredParameter.js
src/rest.js -> lib/rest.js
src/triggers.js -> lib/triggers.js
src/vendor/mongodbUrl.js -> lib/vendor/mongodbUrl.js

> parse-server@2.2.24 test /Users/alex/dev/parse/parse-server
> cross-env MONGODB_VERSION=${MONGODB_VERSION:=3.2.6} MONGODB_STORAGE_ENGINE=mmapv1 NODE_ENV=test TESTING=1 node $COVERAGE_OPTION ./node_modules/jasmine/bin/jasmine.js

Started
............................................Configuration loaded from /Users/alex/dev/parse/parse-server/spec/configs/CLIConfig.json
...Configuration loaded from /Users/alex/dev/parse/parse-server/spec/configs/CLIConfigApps.json
.................................*.......................*.....................*.................................................................................................................*.........................................................................................................................................................................................................................*........*.....................................................................*.............................*..........*.........*..................................................................................................................*..................*..*.*.........*...............................................................................................**...........................................................................................*..........F...***..............................................................................*................................................*..........................

Failures:
1) rest create test specified session length
  Message:
    Expected 34 to equal 33.
  Stack:
    Error: Expected 34 to equal 33.
        at /Users/alex/dev/parse/parse-server/spec/RestCreate.spec.js:385:37
        at process._tickDomainCallback (node.js:412:9)
Pending:

1) Cloud Code test afterSave ignoring promise, object not found
  Temporarily disabled with xit


2) Cloud Code should fully delete objects when using `unset` with beforeSave (regression test for #1840)
  Temporarily disabled with xit


3) Cloud Code Logger should log a changed beforeSave indicating a change
  needs more work.....


4) parseObjectToMongoObjectForCreate a delete op
  Temporarily disabled with xit


5) Installations creating multiple devices with same device token works
  Temporarily disabled with xit


6) Installations update ios device token with duplicate token different app
  Temporarily disabled with xit


7) Parse.Object testing can set null
  Temporarily disabled with xit


8) Parse.Object testing saving children in an array
  Temporarily disabled with xit


9) Parse.Object testing bytes work
  Temporarily disabled with xit


10) Parse.Object testing fetchAll User attributes get merged
  Temporarily disabled with xit


11) Parse.Query testing querying for null value
  Temporarily disabled with xit


12) Parse.Relation testing queries with relations
  Temporarily disabled with xit


13) Parse.Relation testing query on pointer and relation fields with equal
  Temporarily disabled with xit


14) Parse.Relation testing or queries on pointer and relation fields
  Temporarily disabled with xit


15) Parse Role testing should not recursively load the same role multiple times
  Temporarily disabled with xit


16) Parse.User testing should cleanup null authData keys (regression test for #935)
  Temporarily disabled with xit


17) Parse.User testing should not serve null authData keys
  Temporarily disabled with xit


18) rest create handles object and subdocument
  Temporarily disabled with xit


19) rest query query for user w/ legacy credentials without masterKey has them stripped from results
  Temporarily disabled with xit


20) rest query query for user w/ legacy credentials with masterKey has them stripped from results
  Temporarily disabled with xit


21) rest query query with include
  Temporarily disabled with xit


22) schemas lets you delete multiple fields and add fields
  Temporarily disabled with xit


23) Uniqueness can do compound uniqueness
  Temporarily disabled with xit

1098 specs, 1 failure, 23 pending specs
Finished in 228.737 seconds

File [/Users/alex/dev/parse/parse-server/src/Adapters/Files/FilesAdapter.js] ignored, nothing could be mapped
File [/Users/alex/dev/parse/parse-server/src/Adapters/Cache/CacheAdapter.js] ignored, nothing could be mapped
File [/Users/alex/dev/parse/parse-server/src/Adapters/Email/MailAdapter.js] ignored, nothing could be mapped
File [/Users/alex/dev/parse/parse-server/src/Adapters/Push/PushAdapter.js] ignored, nothing could be mapped

=============================== Coverage summary ===============================
Statements   : 84.18% ( 6000/7128 )
Branches     : 77.25% ( 3267/4229 )
Functions    : 82.7% ( 999/1208 )
Lines        : 84.03% ( 5767/6863 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

**Comment by flovilmart** [comment]
Rebase on the master branch, it should all pass fine according to travis.
