### ISSUE TITLE
Display error SeleniumProcess.pid: Undefined events.js:141 when run command webdriver-manager start 

### ISSUE THREAD

**Issue by rohanghatage6289** [ParsePlatform/parse-server#3028]
C:\Users\rohan.ghatage>webdriver-manager start
[12:43:15] I/start - java -Dwebdriver.chrome.driver=C:\Users\rohan.ghatage\AppDa
ta\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\c
hromedriver_2.24.exe -Dwebdriver.gecko.driver=C:\Users\rohan.ghatage\AppData\Roa
ming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodr
iver-v0.9.0.exe -jar C:\Users\rohan.ghatage\AppData\Roaming\npm\node_modules\pro
tractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-2.53.
1.jar
[12:43:15] I/start - seleniumProcess.pid: undefined
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by flovilmart** [comment]
Not sure how it is related to parse-server, can you reopen with all the issue template filled correctly?
