### ISSUE TITLE
Error after migrating data to MongoDB

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/parse-server#304]
I deployed Parse server on Heroku. Everything worked great when database was blank, I even tried creating , updating, and fetching objects from it to test. Worked amazing. 

I started migration process from Parse, and now I am in the stage where I would like to verify that data is working. I haven't pressed finish migration on Parse.com. Want to test my own parse server first. 

Data is in the DB. Everything looks good. When I try to fetch objects from it I get this error in Xcode: 

```
[Error]: {"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)
[error: {"code":1,"message":"Internal server error."}, NSLocalizedDescription: {"code":1,"message":"Internal server error."}, code: 1]
```

Heroku Logs show this: 

```
2016-02-08T21:25:51.046324+00:00 app[web.1]: Uncaught internal server error. [Error: Invalid mongoURI: URL IS HERE HIDING FOR SECURITY] Error: Invalid mongoURI: URL IS HERE HIDING FOR SECURITY
2016-02-08T21:25:51.046328+00:00 app[web.1]:     at ExportAdapter.connect (/app/node_modules/parse-server/ExportAdapter.js:39:11)
2016-02-08T21:25:51.046331+00:00 app[web.1]:     at new Config (/app/node_modules/parse-server/Config.js:16:35)
2016-02-08T21:25:51.046334+00:00 app[web.1]:     at trim_prefix (/app/node_modules/parse-server/node_modules/express/lib/router/index.js:312:13)
2016-02-08T21:25:51.046335+00:00 app[web.1]:     at Function.process_params (/app/node_modules/parse-server/node_modules/express/lib/router/index.js:330:12)
```

I checked my Mongo URI and it looks good. Not sure what the issue is.

**Comment by talkaboutdesign** [comment]
Looks like its in relationship to this issue, when changed database to production Mongodb URL has this prefixed:
`?replicaSet=rs-ds829292`

**Comment by adamontherun** [comment]
@talkaboutdesign its [this issue](https://github.com/ParsePlatform/parse-server/pull/148#issuecomment-181161174) that's causing it to fail

**Comment by remiprev** [comment]
I think this has been solved by https://github.com/ParsePlatform/parse-server/pull/297, right? `parse-server@2.0.8` works correctly for me with a MongoDB replica set URI.

**Comment by gfosco** [comment]
Assuming this was fixed.  If there is a problem with the latest version, please open a new issue.  Thanks.
