### ISSUE TITLE
Issue after migrating to Parse Server

### ISSUE THREAD

**Issue by kumarkeviv** [ParsePlatform/parse-server#317]
Hi All

I had migrated one of my app db to Mongo Lab and hosted the Parse Server on Azure with standard procedure and parse server is running fine there. Then I updated my Parse SDK to latest 1.13.0 as instructed and redirected my app to new hosted Parse Server... But when i launch my app any Parse query is not working.

Here is logcat:

FATAL EXCEPTION: main Process: com.phoenixapplabs.hrinterview, PID: 23555
java.lang.NoClassDefFoundError: bolts.TaskCompletionSource
at com.parse.ParseQuery$3$1.then(ParseQuery.java:1222)
at com.parse.ParseQuery$3$1.then(ParseQuery.java:1218)
at bolts.Task$14.run(Task.java:796)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeAfterTask(Task.java:787)
at bolts.Task.continueWithTask(Task.java:599)
at bolts.Task.continueWithTask(Task.java:610)
at bolts.Task$12.then(Task.java:702)
at bolts.Task$12.then(Task.java:690)
at bolts.Task$14.run(Task.java:796)
at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:105)
at bolts.Task.completeAfterTask(Task.java:787)
at bolts.Task.continueWithTask(Task.java:599)
at bolts.Task.continueWithTask(Task.java:574)
at bolts.Task.onSuccessTask(Task.java:690)
at bolts.Task.onSuccessTask(Task.java:680)
at bolts.Task.onSuccessTask(Task.java:714)
at com.parse.ParseQuery$3.call(ParseQuery.java:1218)
at com.parse.ParseQuery$3.call(ParseQuery.java:1215)
at com.parse.ParseQuery.doWithRunningCheck(ParseQuery.java:1154)
at com.parse.ParseQuery.findAsync(ParseQuery.java:1215)
at com.parse.ParseQuery.findInBackground(ParseQuery.java:1202)
at com.phoenixapplabs.hrinterview.Login_Multiple.parse_registration(Login_Multiple.java:717)
at com.phoenixapplabs.hrinterview.Login_Multiple.onResult(Login_Multiple.java:695)
at com.phoenixapplabs.hrinterview.Login_Multiple.onResult(Login_Multiple.java:71)
at com.google.android.gms.common.api.AbstractPendingResult$CallbackHandler.deliverResultCallback(Unknown Source)
at com.google.android.gms.common.api.AbstractPendingResult$CallbackHandler.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:149)
at android.app.ActivityThread.main(ActivityThread.java:5257)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
at dalvik.system.NativeStart.main(Native Method)

What is the issue? I don't know how to proceed plz help.

**Comment by drew-gross** [comment]
Can you run the server with VERBOSE=1 and tell us what the output is when you make the failing query? If there is no output, then this is probably an issue with the Android SDK, in which case you should open an issue with the Android SDK repo.

**Comment by kumarkeviv** [comment]
I don't know how to turn the verbose=1 in azure for webapp, could you guide the steps because i can only see verbose in azure for their cloud services.

**Comment by drew-gross** [comment]
VERBOSE is an environment variable, you set it the same way as any other environment variable.

**Comment by christianmarth** [comment]
Have you also updated the bolts framework? It appears the no class def
error relates to Bolts

On Wednesday, 10 February 2016, Drew <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:

> VERBOSE is an environment variable, you set it the same way as any other
> environment variable.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ParsePlatform/parse-server/issues/317#issuecomment-182199720>
> .
>


-- 

Kind Regards

Christian Marth | Director



*App Fibre (Singapore) Pte. Ltd.*
8 Jurong Town Hall Road
The JTC Summit #24-05
Singapore 609434
*Phone: *+65 8142 5242
*UEN: *201419241N
*Facebook: *facebook.com/appfibre <https://www.facebook.com/appfibre>

*Skype: *christian.marth
*LinkedIn: *au.linkedin.com/in/christianmarth


*Our company accepts no liability for the content of this email, or for the
consequences of any actions taken on the basis of the information provided,
unless that information is subsequently confirmed in writing. If you are
not the intended recipient you are notified that disclosing, copying,
distributing or taking any action in reliance on the contents of this
information is strictly prohibited.*

**Comment by kumarkeviv** [comment]
Hi Drew and Christian

The previous issue is resolved it was the SDK's issue as Drew suggested.

Now when I am hitting the parse server hosted on Azure, I am not getting any response its just throwing an exception that JSON response is not in correct format.

I have hosted my parse server here: http://hr-interview.azurewebsites.net/

Also my definition for Initialization in Application file of app is here:

  Parse.initialize(new Parse.Configuration.Builder(getBaseContext())
                        .applicationId("xxxxxxxxxxxxxxxxxxxx")
                        .clientKey("xxxxxxxxxxxxxxxxxxxxx")
                        .server("http://hr-interview.azurewebsites.net")
                        .build()
        );

I am using the same appid and client id i was using in parse. Am I missing something?

**Comment by drew-gross** [comment]
Incorrect JSON format sounds more like a parse-server issue. Can you use the VEBOSE environment variable like I mentioned above and paste the output of the server here?

**Comment by kumarkeviv** [comment]
Hi Drew

I have enabled the verbose=1, also i have downloaded the diagnostics files. But I can't find much in the log. I can see that the request is hitting cloud as the REQUEST is visible on dashboard.

Please find the trace I got at this link:
https://www.dropbox.com/sh/f0e7oxqkckancow/AACz5QNbtd212exx6yw8ob_ia?dl=0

Let me know, if i need to do anything more.

**Comment by drew-gross** [comment]
There are a lot of files in that folder. With VERBOSE enabled, you should see an request body and response in your server's output. Can you paste the output for a single failing request here?

**Comment by kumarkeviv** [comment]
Hi Drew

The issue has been resolved, and you can close this now. Thanks for your help.

**Comment by otymartin** [comment]
@kumarkeviv What was your solution?

**Comment by mjoshinath** [comment]
Hi Guys, i have the same issue as mentioned above  and i have tried setting VERBOSE value to 1 and even then no change

**Comment by drew-gross** [comment]
We determined that this issue is an Android SDK issue, can you check the Android SDK repo for help?

**Comment by mjoshinath** [comment]
Hey drew, problem solved but with upgradation of facebook sdk dependency to 4.9.0, Thanks
