### ISSUE TITLE
Parse-server installation issues on heroku

### ISSUE THREAD

**Issue by rosarioconti** [ParsePlatform/parse-server#320]
HI
  I tried to install Parse-server module 2.0.7 but also happening with previous version until 2.0.4
 but I'm getting some issue. 

Something looks missing.  Any idea why I can't install the latest ? and just to be sure is the 2.0.7 latest at this point? 

 thanks 

2016-02-08T23:41:09.076672+00:00 app[web.1]: module.js:341
2016-02-08T23:41:09.076674+00:00 app[web.1]: throw err;
2016-02-08T23:41:09.076675+00:00 app[web.1]: ^
2016-02-08T23:41:09.076675+00:00 app[web.1]: 
2016-02-08T23:41:09.076676+00:00 app[web.1]: Error: Cannot find module './password'
2016-02-08T23:41:09.076677+00:00 app[web.1]: at Function.Module._resolveFilename (module.js:339:15)
2016-02-08T23:41:09.076677+00:00 app[web.1]: at Function.Module._load (module.js:290:25)
2016-02-08T23:41:09.076678+00:00 app[web.1]: at Module.require (module.js:367:17)
2016-02-08T23:41:09.076678+00:00 app[web.1]: at require (internal/module.js:16:19)
2016-02-08T23:41:09.076679+00:00 app[web.1]: at Object. (/app/node_modules/parse-server/RestWrite.js:12:22)
2016-02-08T23:41:09.076680+00:00 app[web.1]: at Module._compile (module.js:413:34)
2016-02-08T23:41:09.076680+00:00 app[web.1]: at Object.Module._extensions..js (module.js:422:10)
2016-02-08T23:41:09.076681+00:00 app[web.1]: at Module.load (module.js:357:32)
2016-02-08T23:41:09.076681+00:00 app[web.1]: at Function.Module._load (module.js:314:12)
2016-02-08T23:41:09.076684+00:00 app[web.1]: at Module.require (module.js:367:17)

**Comment by globyworks** [comment]
Have you tried deploying Parse server using the Heroku button at https://github.com/ParsePlatform/parse-server-example ?

**Comment by rosarioconti** [comment]
I'm doing an update, not first time installation, what's not clear? but anyway...
  I found out the route cause, it was involuntary commit of the node_modules where that module was missing.
 So, now its working.

**Comment by rosarioconti** [comment]
You can close it.
