### ISSUE TITLE
Error when run Cloud Code job - property 'extend' of undefined

### ISSUE THREAD

**Issue by luishscosta** [ParsePlatform/parse-server#3241]
When I try run a job I recieve the following message:

```
Dec 15 17:11:51 parse-lw parse-server: /usr/lib/node_modules/parse-server/lib/ParseServer.js:437
Dec 15 17:11:51 parse-lw parse-server: throw err;
Dec 15 17:11:51 parse-lw parse-server: ^
Dec 15 17:11:51 parse-lw parse-server: TypeError: Cannot read property 'extend' of undefined
Dec 15 17:11:51 parse-lw parse-server: at consultaLojas (/usr/lib/node_modules/parse-server/cloud/main.js:25:44)
Dec 15 17:11:51 parse-lw parse-server: at /usr/lib/node_modules/parse-server/cloud/main.js:4:5
Dec 15 17:11:51 parse-lw parse-server: at /usr/lib/node_modules/parse-server/lib/Routers/FunctionsRouter.js:106:11
Dec 15 17:11:51 parse-lw parse-server: at nextTickCallbackWith0Args (node.js:420:9)
Dec 15 17:11:51 parse-lw parse-server: at process._tickDomainCallback (node.js:390:13)
```

On my main.js I have this code:

```
var LojasCollection = Parse.Collection.extend({
                model: objLojas,
                query: queryLojas
            });
```

I'm not having this problem using the parse.com app. I tried to install parsebone module, but I did not succeed.

**Comment by lenart** [comment]
You're trying to use `Parse.Collection` which doesn't exist anymore in the latest Parse SDK. Read this [stackoverflow comment](http://stackoverflow.com/a/32827781/289594) for more details.
