### ISSUE TITLE
Connection to MongoLab

### ISSUE THREAD

**Issue by soniurvashi11** [ParsePlatform/parse-server#3281]
i m trying to connect parse server on my local with my db present on mongolab with the specific uri ,parse server runs successfully -

> appId: gtgUU5L9gGPiHCAlLf0euOhgjbn8ieWoF0gwgYFr
> masterKey: ***REDACTED***
> port: 1337
> host: 0.0.0.0
> databaseURI: mongodb://magadmin-urvashi:q1Qqqqqqq@ds021172.mlab.com:21172/magnif
> icentmdbdev
> mountPath: /parse
> maxUploadSize: 20mb
> userSensitiveFields: email
> serverURL: http://localhost:1337/parse

But still wen i run my php-sdk based app and try to login it says-

> exception 'Parse\ParseException' with message 'unauthorized' in C:\xampp\htdocs\Magnificent\vendor\parse\php-sdk\src\Parse\ParseClient.php:375 Stack trace: #0 C:\xampp\htdocs\Magnificent\vendor\parse\php-sdk\src\Parse\ParseUser.php(133): Parse\ParseClient::_request('GET', 'login', '', Array) #1 C:\xampp\htdocs\Magnificent\application\controllers\login.php(31): Parse\ParseUser::logIn('admin', 'admin123') #2 [internal function]: login->login_user() #3 C:\xampp\htdocs\Magnificent\system\core\CodeIgniter.php(359): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\Magnificent\index.php(203): require_once('C:\\xampp\\htdocs...') #5 {main}

Can anybody help/suggest the correct way?

**Comment by natanrolnik** [comment]
@soniurvashi11 do you have any updates since you opened this issue? How do you initialize your php SDK?

**Comment by natanrolnik** [comment]
Closing due to inactivity.

**Comment by soniurvashi11** [comment]
@natanrolnik  ya .. I had to update my php sdk..and it worked for me :)
