### ISSUE TITLE
Cannot find module './defaults'

### ISSUE THREAD

**Issue by newdev7** [ParsePlatform/parse-server#3349]
Till today I've used parse-server 2.2.18 in my app. I tried to update the parse-server to the newer version(2.3.2). After installed the new version, I tested locally. It doesn't throw any errors. I pushed the code to heroku and tested. This time it throws an error. It shows
```
Error: Cannot find module './defaults'
at Function.Module._resolveFilename (module.js:339:15)
at Function.Module._load (module.js:290:25)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> (/app/node_modules/parse-server/lib/ParseServer.js:9:17)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
```

When I check the code in ParseServer.js file, it requires the './default' module. But that module was not present.

How to fix this error. Thanks.

**Comment by natanrolnik** [comment]
I think it might be related to clearing the cache of npm.
Can you try setting `heroku config:set NODE_MODULES_CACHE=false` or set manually to false in the app's dashboard?

**Comment by hramos** [comment]
Hey, thanks for reporting this issue.

Can you please add all the info specified in the [template](https://github.com/ParsePlatform/parse-server/blob/master/.github/ISSUE_TEMPLATE.md)? This is necessary for people to be able to understand and reproduce the issue being reported.
