### ISSUE TITLE
[Help] Push Notification Certificate has expired

### ISSUE THREAD

**Issue by makoy21** [ParsePlatform/parse-server#3479]
Hi I'am getting this error when sending push notification from dashboard and via code.

This my code:  
```
Parse.Push.send({
        where: query,
        data: {
            title: title,
            alert: message,
            page: page
        }
    }, {
        success: function() {
            console.log(message);
        },
        error: function(error) {
            // Handle error
        }
    });
}
```

This the error I'm getting.
```
Error: certificate has expired: 2017-02-04T07:11:57.000Z
    at validateCredentials (/root/parse-server/node_modules/apn/lib/credentials/validate.js:12:9)
    at /root/parse-server/node_modules/apn/lib/connection.js:163:5
    at _fulfilled (/root/parse-server/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/root/parse-server/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/root/parse-server/node_modules/q/q.js:796:13)
    at /root/parse-server/node_modules/q/q.js:604:44
    at runSingle (/root/parse-server/node_modules/q/q.js:137:13)
    at flush (/root/parse-server/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
/root/parse-server/node_modules/parse-server/lib/ParseServer.js:437
            throw err;
```

**Comment by NatanRolnik** [comment]
@makoy21 push notifications certificates from Apple are valid only for one year, expiring after that. That's was happened to yours. 
Create a new one in developer.apple.com and update it in your Parse Server.

**Comment by makoy21** [comment]
Hi how can i handle that error without crash the parse server?
