### ISSUE TITLE
can not login or register account. bad json response error

### ISSUE THREAD

**Issue by mginz83** [ParsePlatform/parse-server#3549]
`        Parse.enableLocalDatastore(this);

        Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId("MY-APP-ID")
                .clientKey("CLIENT-ID")
                .server("http://appname.herokuapp.com/parse")

                .build()
        );

        //ParseUser.enableAutomaticUser();
        ParseACL defaultACL = new ParseACL();
        // Optionally enable public read access.
        // defaultACL.setPublicReadAccess(true);
        ParseACL.setDefaultACL(defaultACL, true);`

Here is my main app info. I am using 
    compile 'com.parse:parse-android:1.13.1'

Even if I create a new heroku structure, i get the same bad response error.
I have two devices that I am testing, one on nougat and the marshmellow

it was working fine until I started playing around with parse-server-example inside heroku. I removed it, I am not received a bad login for mongodb. so I figure I would start a new project on heroku to see if that fixed it, nope.

**Comment by flovilmart** [comment]
try to set server to: `"http://appname.herokuapp.com/parse/"`

**Comment by mginz83** [comment]
That didnt work. When I restart the DYNOs in heroku, regardless of the application running.

Inside of Heroku, I have the SERVER_URI set to http://appname.herokuapp.com/parse/

**Comment by mginz83** [comment]
`
2017-02-21T16:23:42.967010+00:00 heroku[web.1]: State changed from starting to up
2017-02-21T16:23:46.651168+00:00 heroku[web.1]: Restarting
2017-02-21T16:23:46.652576+00:00 heroku[web.1]: State changed from up to starting
2017-02-21T16:23:47.467242+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2017-02-21T16:23:47.737276+00:00 heroku[web.1]: Process exited with status 143
2017-02-21T16:23:49.646871+00:00 heroku[web.1]: Starting process with command `npm start`
2017-02-21T16:23:52.155583+00:00 app[web.1]: 
2017-02-21T16:23:52.155601+00:00 app[web.1]: > parse-server-example@1.4.0 start /app
2017-02-21T16:23:52.155602+00:00 app[web.1]: > node index.js
2017-02-21T16:23:52.155603+00:00 app[web.1]: 
2017-02-21T16:23:54.035695+00:00 heroku[web.1]: State changed from starting to up
2017-02-21T16:23:54.009256+00:00 app[web.1]: parse-server-example running on port 7276.
2017-02-21T16:23:54.085042+00:00 app[web.1]: [33mwarn[39m: Unable to ensure uniqueness for usernames:  MongoError: Authentication failed.
2017-02-21T16:23:54.085044+00:00 app[web.1]:     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2017-02-21T16:23:54.085046+00:00 app[web.1]:     at /app/node_modules/mongodb-core/lib/connection/pool.js:483:72
2017-02-21T16:23:54.085046+00:00 app[web.1]:     at authenticateStragglers (/app/node_modules/mongodb-core/lib/connection/pool.js:429:16)
2017-02-21T16:23:54.085047+00:00 app[web.1]:     at Connection.messageHandler (/app/node_modules/mongodb-core/lib/connection/pool.js:463:5)
2017-02-21T16:23:54.085048+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:319:22)
2017-02-21T16:23:54.085048+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-02-21T16:23:54.085049+00:00 app[web.1]:     at Socket.emit (events.js:189:7)
2017-02-21T16:23:54.085050+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2017-02-21T16:23:54.085051+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:134:10)
2017-02-21T16:23:54.085051+00:00 app[web.1]:     at TCP.onread (net.js:551:20)
2017-02-21T16:23:54.086060+00:00 app[web.1]: [33mwarn[39m: Unable to ensure uniqueness for user email addresses:  MongoError: Authentication failed.
2017-02-21T16:23:54.086062+00:00 app[web.1]:     at Function.MongoError.create (/app/node_modules/mongodb-core/lib/error.js:31:11)
2017-02-21T16:23:54.086063+00:00 app[web.1]:     at /app/node_modules/mongodb-core/lib/connection/pool.js:483:72
2017-02-21T16:23:54.086063+00:00 app[web.1]:     at authenticateStragglers (/app/node_modules/mongodb-core/lib/connection/pool.js:429:16)
2017-02-21T16:23:54.086064+00:00 app[web.1]:     at Connection.messageHandler (/app/node_modules/mongodb-core/lib/connection/pool.js:463:5)
2017-02-21T16:23:54.086065+00:00 app[web.1]:     at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:319:22)
2017-02-21T16:23:54.086066+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-02-21T16:23:54.086066+00:00 app[web.1]:     at Socket.emit (events.js:189:7)
2017-02-21T16:23:54.086067+00:00 app[web.1]:     at readableAddChunk (_stream_readable.js:176:18)
2017-02-21T16:23:54.086067+00:00 app[web.1]:     at Socket.Readable.push (_stream_readable.js:134:10)
2017-02-21T16:23:54.086068+00:00 app[web.1]:     at TCP.onread (net.js:551:20)
2017-02-21T16:23:54.087388+00:00 app[web.1]: (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): MongoError: Authentication failed.
2017-02-21T16:23:54.087660+00:00 app[web.1]: (node:17) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2017-02-21T16:23:54.088267+00:00 app[web.1]: (node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): MongoError: Authentication failed.
`

This is what I am getting when I reset the dyno. It is still looking for parse-server-example when I am not using that...

**Comment by flovilmart** [comment]
your mongodb credentials are wrong, "MongoError: Authentication failed. "

**Comment by mginz83** [comment]
That's what I figured as well but it is still not working after I reset the password

**Comment by mginz83** [comment]
Is there a way to see what password index.js is trying to use. BC I change it on mongo, update MongoDB on heroku, but it still didn't work.

**Comment by flovilmart** [comment]
the username and password authentication for mongodb is part of the databaseUrihttp://parseplatform.github.io/docs/parse-server/guide/#usage option

**Comment by mginz83** [comment]
Yeah. I formed that parse server example. Inside of heroku I went over to deploy, searched for my parse server example, connect it and then enabled auto update. I edited the credentials in parse server example on GitHub and same error.

Every was working fine prior.... Very frustrating.

**Comment by mginz83** [comment]
Is there a way to go back to the API keys (master and app) as well as the original MongoDB user name and password from when I first started it?

Perhaps that's the problem? I changed it over at mongo and it didn't reflect within the index.js?

My last thing I'm gonna do it start completely over with a new heroku deployment as well as a new Android project.

**Comment by flovilmart** [comment]
You should probably make it work on your local machine instead of focusing on Heroku and yes you can do pretty much anything you want.

**Comment by mginz83** [comment]
Can you talk to me a little bit about doing it locally. The app I am building it a pretty large project that I hope one day a ton of people are using. If it's done locally and my PC  is off, for example, no code can run, right?

**Comment by flovilmart** [comment]
I meant to familiarize yourself with the configuration, deployments etc... visit http://parseplatform.github.io/docs for all docs around Parse-server

**Comment by mginz83** [comment]
I'm good with the docs bro. I have a few apps on Android running a parse back end with heroku/mongo. Somehow I broke this one and I can't figure out why

**Comment by flovilmart** [comment]
Also, It seems that all your credentials are public on your parse-server-example 'bro'.
