### ISSUE TITLE
Parse.Cloud.httpRequest not working on heroku

### ISSUE THREAD

**Issue by ktmatzdorf** [ParsePlatform/parse-server#484]
I am doing a POST request with x-www-url encoded payload to mailchimp in a cloud function via Parse.Cloud.httpRequest.
Might it depend on new Buffer call within the httpRequest file? https://github.com/ParsePlatform/parse-server/blob/master/src/httpRequest.js
Is anyone else experiencing a similar problem?

**Comment by flovilmart** [comment]
What is not working?

**Comment by ktmatzdorf** [comment]
Sorry for responding late. I think my problem is related to #727 and #703 but to be more precise i got this back:
```
SyntaxError: Unexpected token c
2016-03-01T08:27:47.049324+00:00 app[web.1]:     at parse (/app/node_modules/body-parser/lib/types/json.js:83:15)
2016-03-01T08:27:47.049325+00:00 app[web.1]:     at /app/node_modules/body-parser/lib/read.js:116:18
2016-03-01T08:27:47.049325+00:00 app[web.1]:     at invokeCallback (/app/node_modules/raw-body/index.js:262:16)
2016-03-01T08:27:47.049326+00:00 app[web.1]:     at done (/app/node_modules/raw-body/index.js:251:7)
2016-03-01T08:27:47.049326+00:00 app[web.1]:     at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:308:7)
```
I think it has to do with not using compression by request/and or parse server. I don´t know what express version run on parse but 4.x needs explicitly compression for compressed request and request needs (gzip) enabled manually.
