### ISSUE TITLE
Parse Server Heroku Twitter Oauth

### ISSUE THREAD

**Issue by talkaboutdesign** [ParsePlatform/parse-server#496]
Hey guys, 

What do I need to change in order to make my app work again with Twitter Signin. I am using ParseTwitterUtils on iOS side. What change should I make on the server? 

Sorry for being a noob on this.

**Comment by talkaboutdesign** [comment]
When I try to login through the app, I get the following log trace on Heroku.

`2016-02-19T02:21:35.281101+00:00 app[web.1]: Uncaught internal server error. [TypeError: Cannot read property 'consumer_key' of undefined] TypeError: Cannot read property 'consumer_key' of undefined
2016-02-19T02:21:35.281107+00:00 app[web.1]:     at new OAuth (/app/node_modules/parse-server/lib/oauth/OAuth1Client.js:7:30)
2016-02-19T02:21:35.281110+00:00 app[web.1]:     at RestWrite.handleOAuthAuthData (/app/node_modules/parse-server/lib/RestWrite.js:262:10)
2016-02-19T02:21:35.281110+00:00 app[web.1]:     at RestWrite.validateAuthData (/app/node_modules/parse-server/lib/RestWrite.js:166:19)
2016-02-19T02:21:35.281112+00:00 app[web.1]:     at process._tickDomainCallback (node.js:445:9)`

**Comment by drew-gross** [comment]
Check out the OAuth Support section of the readme. Keep in mind you will need to be on the latest version of Parse Server (2.1.1)
