### ISSUE TITLE
Can not update Schema via Schema API

### ISSUE THREAD

**Issue by ntloc592** [ParsePlatform/parse-server#848]
- I can not delete **a field or column(type: Relation)** from any schema
- Result:
{
    "code": 1,
    "message": "Internal server error."
}

With exception from code

Uncaught internal server error. { [MongoError: ns not found]
name: 'MongoError',message: 'ns not found', ok: 0, errmsg: 'ns not found' }
MongoError: ns not found at Function.MongoError.create (E:\Parse\parse-server-2-1-4\node_modules\mongodb\node_modules\mongodb-core\lib\error.js:31:11)
    at commandCallback (E:\Parse\parse-server-2-1-4\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:929:66)
    at Callbacks.emit (E:\Parse\parse-server-2-1-4\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:116:3)
    at null.messageHandler (E:\Parse\parse-server-2-1-4\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:282:23)
    at Socket.<anonymous> (E:\Parse\parse-server-2-1-4\node_modules\mongodb\node_modules\mongodb-core\lib\connection\connection.js:273:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10) at TCP.onread (net.js:523:20)

**Comment by gfosco** [comment]
Will be fixed by #864.  Thanks for catching this. :+1:
