### ISSUE TITLE
Can't start parse server

### ISSUE THREAD

**Issue by iulianvarzaru** [ParsePlatform/parse-server#95]
I installed everything correctly and npm install didn't returned any errors but when I try to start the server I get the following error:

`/home/iulian/public_html/api.frimba.com/node_modules/parse-server/index.js:153
    request(options, (error, response, body) => {
                                              ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/iulian/public_html/api.frimba.com/index.js:5:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)`

I just used the parse-server-example and changed a few things.

**Comment by Martijnvdc** [comment]
I have had the same issue.
The problem is the Node version you're running.
Run the following commands in bash:

nvm install 4.1
npm install npm -g

Then try to run your server again.

**Comment by gfosco** [comment]
Yes, parse-server requires Node >= 4.1
