### ISSUE TITLE
login with twitter error in PFLoginViewController

### ISSUE THREAD

**Issue by kenjiIdo** [ParsePlatform/parse-server#973]
Hi,
I can't login with twitter with using ParseTwitterUtils.
{"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)

typed in AppDelegate.m
[PFTwitterUtils initializeWithConsumerKey:@"xxxxxxxxxxxxxxxxxxxxx"
                               consumerSecret:@"xxxxxxxxxxxxxxxxxxxxx"];

then 
PFLogInViewController *logInController = [[DFParseLogInViewController alloc] init];
    logInController.fields = PFLogInFieldsDefault | PFLogInFieldsFacebook | PFLogInFieldsTwitter;
    logInController.delegate= self;

i got the below message:
"Login failed"
{"code":1,"message":"Internal server error."} (Code: 1, Version: 1.12.0)

but it's ok when i use fabric & twitterkit sdk.

please help me.

**Comment by flovilmart** [comment]
Can you provide the server logs when running with VERBOSE?

**Comment by kenjiIdo** [comment]
![screen shot 2016-03-12 at 00 48 55](https://cloud.githubusercontent.com/assets/17334528/13707279/3fe2230e-e7ec-11e5-950e-ae4b1916896a.png)

I am not sure 'VERBOSE=1'

I use heroku server.
here is server logs.

2016-03-11T15:48:34.402188+00:00 app[web.1]: Uncaught internal server error. [TypeError: Cannot read property 'consumer_key' of undefined] TypeError: Cannot read property 'consumer_key' of undefined

2016-03-11T15:48:34.402223+00:00 app[web.1]:     at new OAuth (/app/node_modules/parse-server/lib/oauth/OAuth1Client.js:7:30)

2016-03-11T15:48:34.402224+00:00 app[web.1]:     at validateAuthData (/app/node_modules/parse-server/lib/oauth/twitter.js:9:16)

2016-03-11T15:48:34.402224+00:00 app[web.1]:     at RestWrite.handleOAuthAuthData (/app/node_modules/parse-server/lib/RestWrite.js:334:10)

2016-03-11T15:48:34.402225+00:00 app[web.1]:     at RestWrite.validateAuthData (/app/node_modules/parse-server/lib/RestWrite.js:238:19)

2016-03-11T15:48:34.402226+00:00 app[web.1]:     at /app/node_modules/parse-server/lib/RestWrite.js:81:18

2016-03-11T15:48:34.402226+00:00 app[web.1]:     at run (/app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:84:47)

2016-03-11T15:48:34.402227+00:00 app[web.1]:     at /app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:95:28

2016-03-11T15:48:34.402227+00:00 app[web.1]:     at flush (/app/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:19:5)

2016-03-11T15:48:34.402228+00:00 app[web.1]:     at _combinedTickCallback (node.js:370:9)

2016-03-11T15:48:34.402229+00:00 app[web.1]:     at process._tickDomainCallback (node.js:425:11)

2016-03-11T15:48:34.402188+00:00 app[web.1]: Uncaught internal server error. [TypeError: Cannot read property 'consumer_key' of undefined] TypeError: Cannot read property 'consumer_key' of undefined

2016-03-11T15:48:34.402223+00:00 app[web.1]:     at new OAuth (/app/node_modules/parse-server/lib/oauth/OAuth1Client.js:7:30)

2016-03-11T15:48:34.402224+00:00 app[web.1]:     at validateAuthData (/app/node_modules/parse-server/lib/oauth/twitter.js:9:16)

2016-03-11T15:48:34.402224+00:00 app[web.1]:     at RestWrite.handleOAuthAuthData (/app/node_modules/parse-server/lib/RestWrite.js:334:10)

2016-03-11T15:48:34.402226+00:00 app[web.1]:     at run (/app/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:84:47)

2016-03-11T15:48:34.402227+00:00 app[web.1]:     at flush (/app/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:19:5)

2016-03-11T15:48:34.402229+00:00 app[web.1]:     at process._tickDomainCallback (node.js:425:11)

2016-03-11T15:48:34.402228+00:00 app[web.1]:     at _combinedTickCallback (node.js:370:9)

2016-03-11T15:48:34.402188+00:00 app[web.1]: Uncaught internal server error. [TypeError: Cannot read property 'consumer_key' of undefined] TypeErr

**Comment by flovilmart** [comment]
Did you set your twitter configuration correctly? 

oauth: {
   twitter:  {
      consumer_key: «  »,
      consumer_secret: «  »
   }
}

**Comment by kenjiIdo** [comment]
yes. correctly.
no problem when i use fabric & twitterkit.

**Comment by kenjiIdo** [comment]
where i configure this info?
oauth: {    twitter:  {       consumer_key: «  »,       consumer_secret: «  »    } }

**Comment by flovilmart** [comment]
ahah! when you start your ParseServer. For now we don't rely on the keys and secret passed by the client to ensure your user has a valid login.

**Comment by kenjiIdo** [comment]
I declared in Appdelegate.m file
[PFTwitterUtils initializeWithConsumerKey:@"EkubAxxxxxxGJApPD"
                               consumerSecret:@"meqxxxxblCOwma"];

**Comment by flovilmart** [comment]
You need to configure it in parse-server

**Comment by kenjiIdo** [comment]
please explain...

**Comment by flovilmart** [comment]
Did you read the documentation relative to OAuth on parse-server that I just posted?

**Comment by kenjiIdo** [comment]
Thank you very much, just done.

**Comment by falsalloum** [comment]
Sorry can you please explain where do you add the oauth? I already have it in the client side using PFTwitterUtils.initializeWithConsumerKey

**Comment by junal** [comment]
@flovilmart I'm using parse server version 2.2.5 at both local and remote server. I have configured twitter login at index.js and using loginWith() to login. It works locally but not with remote server. I'm using AWS Elastic Beans for remote server. Here's sample request ...

```
{
"authData":{
"twitter":{
"id":14303772,
"screen_name":"junal",
"consumer_key":"-----",
"consumer_secret":"---",
"auth_token":"14303772-----",
"auth_token_secret":"---"
}
},
"_ApplicationId":"---",
"_ClientVersion":"js1.9.2",
"_InstallationId":"c24a0cca-------"
}
```
Here's what I get. Any advice?
```
{
  "code": 1,
  "message": "Internal server error."
}
```

**Comment by flovilmart** [comment]
Probably an issue with your deployment to elastic beanstalk, if it works locally.

**Comment by junal** [comment]
@flovilmart Upgrading my local parse-server to latest i.e 2.3.5 worked locally but when I update package.json file to update the same to remove server, it did but then it gave me 502 bad gateway error.

**Comment by flovilmart** [comment]
Again, likely an issue with how you deploy to Elastic Beanstalk. Not sure how you're configured nor how you deploy.

**Comment by junal** [comment]
@flovilmart here's my configuration https://dl.dropboxusercontent.com/spa/e8jedo3lnl7g7wc/bckad01p.png and deploy using "eb deploy"

**Comment by flovilmart** [comment]
From the docs: If git is installed, EB CLI uses the git archive command to create a .zip file from the contents of the most recent git commit command.

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb3-deploy.html

Are all your changes correctly commited?

**Comment by flovilmart** [comment]
Then perhaps the eb_*.logs that may give a pointer as for what went wrong in the deployment

**Comment by kukkadapukarhtik** [comment]
TwitterLoginWithParseExample[2581:116523] Error: Error Domain=com.parse.networking.error Code=-1011 "Expected status code in (200-299), got 410" UserInfo={NSLocalizedDescription=Expected status code in (200-299), got 410, NSErrorFailingURLKey=https://api.parse.com/2/user_signup_or_login} (Code: 100, Version: 1.2.19)

**Comment by flovilmart** [comment]
Can you open the issue on the relevant repository? Seems that you're using an outdated SDK / example that has api.parse.com hardcodded (which is down at the moment)

**Comment by ashish-naik** [comment]
@flovilmart  URL you have posted doesn't have explanation for OAuth.  I have deployed Parse Server on Heroku and using ParseUI for authentication. Facebook authentication is working but for twitter, getting error "twitter auth configuration missing".

I am also not able to find where to setup OAuth. Absolutely feeling clueless. Frankly there are number of .js files that has confused me :)
Where in the documentation do i find all parameters explained in details such as some example files?

Cheers,
Ashish

**Comment by flovilmart** [comment]
you need to set in you parse-server configuration object (alongside your applicationId, masterKey etc...) the oauth configuration:

```
oauth: {
   twitter:  {
      consumer_key: «  »,
      consumer_secret: «  »
   }
}
```

**Comment by ashish-naik** [comment]
Ok got it and it worked. Thanks a lot. 

I am also interested in adding Google authentication using ParseUI. Can you please provide any pointers? I saw one topic but it was closed.

Cheers,
Ashish

**Comment by flovilmart** [comment]
You'll probably need to implement you own login mechanisms (acquiring the access token from Google auth) and then write your own authentication provider which can be based upon the Facebook utils or twitter utils.

**Comment by ashish-naik** [comment]
Ok thanks. Appreciate your quick response. 

Still has one query that i asked above.

Where in the documentation do i find all parameters explained in details such as some example files? 

Parse is very vast application and understanding every parameter is difficult without examples. 

Cheers,
Ashish
