### ISSUE TITLE
[MongoError: server localhost:28017 sockets closed]

### ISSUE THREAD

**Issue by jameslin101** [ParsePlatform/parse-server#995]
Hi - I'm getting the following error when I'm trying to do a get from my local mongo db server. 

```
ncaught internal server error. { [MongoError: server localhost:28017 sockets closed]
  name: 'MongoError',
  message: 'server localhost:28017 sockets closed' } MongoError: server localhost:28017 sockets closed
    at null.<anonymous> (/usr/local/lib/node_modules/parse-server/node_modules/mongodb-core/lib/topologies/server.js:418:49)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at null.<anonymous> (/usr/local/lib/node_modules/parse-server/node_modules/mongodb-core/lib/connection/pool.js:172:10)
    at g (events.js:273:16)
    at emitTwo (events.js:100:13)
    at emit (events.js:185:7)
    at Socket.<anonymous> (/usr/local/lib/node_modules/parse-server/node_modules/mongodb-core/lib/connection/connection.js:153:12)
    at Socket.g (events.js:273:16)
    at emitOne (events.js:90:13)
```

**Comment by jameslin101** [comment]
sorry figured it out - worked if i ran mongod --httpinterface -rest -dbpath /data/db instead of mongodb-runner start
